/* Generated by tools/generate_wm_rows.py from spec/sophia-wm-v1.kdl. */
#include "internal.h"
int sophia_wf_snapshot_output_decode(const void *src, size_t size, struct sophia_wf_snapshot_output *out)
{
    const uint8_t *p = src;
    struct sophia_wf_snapshot_output v;
    if (!src || !out) return -4;
    if (size != 56u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.generation = (uint64_t)wf_get(p + 8, 8);
    v.focus_index = (uint32_t)wf_get(p + 16, 4);
    v.focus_generation = (uint32_t)wf_get(p + 20, 4);
    v.x = (int32_t)wf_signed(p + 24, 4);
    v.y = (int32_t)wf_signed(p + 28, 4);
    v.width = (int32_t)wf_signed(p + 32, 4);
    v.height = (int32_t)wf_signed(p + 36, 4);
    v.work_x = (int32_t)wf_signed(p + 40, 4);
    v.work_y = (int32_t)wf_signed(p + 44, 4);
    v.work_width = (int32_t)wf_signed(p + 48, 4);
    v.work_height = (int32_t)wf_signed(p + 52, 4);
    *out = v;
    return 0;
}
int sophia_wf_snapshot_output_encode(void *dst, size_t size, const struct sophia_wf_snapshot_output *v)
{
    uint8_t p[56];
    if (!dst || !v || size < 56u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->generation, 8);
    wf_put(p + 16, (uint64_t)v->focus_index, 4);
    wf_put(p + 20, (uint64_t)v->focus_generation, 4);
    wf_put(p + 24, (uint64_t)v->x, 4);
    wf_put(p + 28, (uint64_t)v->y, 4);
    wf_put(p + 32, (uint64_t)v->width, 4);
    wf_put(p + 36, (uint64_t)v->height, 4);
    wf_put(p + 40, (uint64_t)v->work_x, 4);
    wf_put(p + 44, (uint64_t)v->work_y, 4);
    wf_put(p + 48, (uint64_t)v->work_width, 4);
    wf_put(p + 52, (uint64_t)v->work_height, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_snapshot_surface_decode(const void *src, size_t size, struct sophia_wf_snapshot_surface *out)
{
    const uint8_t *p = src;
    struct sophia_wf_snapshot_surface v;
    if (!src || !out) return -4;
    if (size != 80u) return -1;
    memset(&v, 0, sizeof(v));
    v.surface_index = (uint32_t)wf_get(p + 0, 4);
    v.surface_generation = (uint32_t)wf_get(p + 4, 4);
    v.state_generation = (uint64_t)wf_get(p + 8, 8);
    v.current_output = (uint64_t)wf_get(p + 16, 8);
    v.capability_bits = (uint16_t)wf_get(p + 24, 2);
    v.kind = (uint16_t)wf_get(p + 26, 2);
    v.request_state_bits = (uint16_t)wf_get(p + 28, 2);
    v.current_state_bits = (uint16_t)wf_get(p + 30, 2);
    v.transient_index = (uint32_t)wf_get(p + 32, 4);
    v.transient_generation = (uint32_t)wf_get(p + 36, 4);
    v.x = (int32_t)wf_signed(p + 40, 4);
    v.y = (int32_t)wf_signed(p + 44, 4);
    v.width = (int32_t)wf_signed(p + 48, 4);
    v.height = (int32_t)wf_signed(p + 52, 4);
    v.min_width = (int32_t)wf_signed(p + 56, 4);
    v.min_height = (int32_t)wf_signed(p + 60, 4);
    v.max_width = (int32_t)wf_signed(p + 64, 4);
    v.max_height = (int32_t)wf_signed(p + 68, 4);
    v.exact_width = (int32_t)wf_signed(p + 72, 4);
    v.exact_height = (int32_t)wf_signed(p + 76, 4);
    *out = v;
    return 0;
}
int sophia_wf_snapshot_surface_encode(void *dst, size_t size, const struct sophia_wf_snapshot_surface *v)
{
    uint8_t p[80];
    if (!dst || !v || size < 80u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->surface_index, 4);
    wf_put(p + 4, (uint64_t)v->surface_generation, 4);
    wf_put(p + 8, (uint64_t)v->state_generation, 8);
    wf_put(p + 16, (uint64_t)v->current_output, 8);
    wf_put(p + 24, (uint64_t)v->capability_bits, 2);
    wf_put(p + 26, (uint64_t)v->kind, 2);
    wf_put(p + 28, (uint64_t)v->request_state_bits, 2);
    wf_put(p + 30, (uint64_t)v->current_state_bits, 2);
    wf_put(p + 32, (uint64_t)v->transient_index, 4);
    wf_put(p + 36, (uint64_t)v->transient_generation, 4);
    wf_put(p + 40, (uint64_t)v->x, 4);
    wf_put(p + 44, (uint64_t)v->y, 4);
    wf_put(p + 48, (uint64_t)v->width, 4);
    wf_put(p + 52, (uint64_t)v->height, 4);
    wf_put(p + 56, (uint64_t)v->min_width, 4);
    wf_put(p + 60, (uint64_t)v->min_height, 4);
    wf_put(p + 64, (uint64_t)v->max_width, 4);
    wf_put(p + 68, (uint64_t)v->max_height, 4);
    wf_put(p + 72, (uint64_t)v->exact_width, 4);
    wf_put(p + 76, (uint64_t)v->exact_height, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_snapshot_action_decode(const void *src, size_t size, struct sophia_wf_snapshot_action *out)
{
    const uint8_t *p = src;
    struct sophia_wf_snapshot_action v;
    if (!src || !out) return -4;
    if (size != 140u) return -1;
    memset(&v, 0, sizeof(v));
    v.action = (uint64_t)wf_get(p + 0, 8);
    v.session_operation_slot = (uint16_t)wf_get(p + 8, 2);
    v.name_len = (uint16_t)wf_get(p + 10, 2);
    memcpy(v.name, p + 12, 128);
    *out = v;
    return 0;
}
int sophia_wf_snapshot_action_encode(void *dst, size_t size, const struct sophia_wf_snapshot_action *v)
{
    uint8_t p[140];
    if (!dst || !v || size < 140u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->action, 8);
    wf_put(p + 8, (uint64_t)v->session_operation_slot, 2);
    wf_put(p + 10, (uint64_t)v->name_len, 2);
    memcpy(p + 12, v->name, 128);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_snapshot_session_operation_decode(const void *src, size_t size, struct sophia_wf_snapshot_session_operation *out)
{
    const uint8_t *p = src;
    struct sophia_wf_snapshot_session_operation v;
    if (!src || !out) return -4;
    if (size != 12u) return -1;
    memset(&v, 0, sizeof(v));
    v.operation = (uint64_t)wf_get(p + 0, 8);
    v.slot = (uint16_t)wf_get(p + 8, 2);
    v.target_bits = (uint16_t)wf_get(p + 10, 2);
    *out = v;
    return 0;
}
int sophia_wf_snapshot_session_operation_encode(void *dst, size_t size, const struct sophia_wf_snapshot_session_operation *v)
{
    uint8_t p[12];
    if (!dst || !v || size < 12u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->operation, 8);
    wf_put(p + 8, (uint64_t)v->slot, 2);
    wf_put(p + 10, (uint64_t)v->target_bits, 2);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_output_decode(const void *src, size_t size, struct sophia_wf_projection_output *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_output v;
    if (!src || !out) return -4;
    if (size != 24u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.placement_count = (uint32_t)wf_get(p + 8, 4);
    v.focus_index = (uint32_t)wf_get(p + 12, 4);
    v.focus_generation = (uint32_t)wf_get(p + 16, 4);
    if (!wf_zero(p + 20, 4)) return -1;
    *out = v;
    return 0;
}
int sophia_wf_projection_output_encode(void *dst, size_t size, const struct sophia_wf_projection_output *v)
{
    uint8_t p[24];
    if (!dst || !v || size < 24u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->placement_count, 4);
    wf_put(p + 12, (uint64_t)v->focus_index, 4);
    wf_put(p + 16, (uint64_t)v->focus_generation, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_placement_decode(const void *src, size_t size, struct sophia_wf_projection_placement *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_placement v;
    if (!src || !out) return -4;
    if (size != 60u) return -1;
    memset(&v, 0, sizeof(v));
    v.surface_index = (uint32_t)wf_get(p + 0, 4);
    v.surface_generation = (uint32_t)wf_get(p + 4, 4);
    v.state_generation = (uint64_t)wf_get(p + 8, 8);
    v.x = (int32_t)wf_signed(p + 16, 4);
    v.y = (int32_t)wf_signed(p + 20, 4);
    v.width = (int32_t)wf_signed(p + 24, 4);
    v.height = (int32_t)wf_signed(p + 28, 4);
    v.requested_width = (int32_t)wf_signed(p + 32, 4);
    v.requested_height = (int32_t)wf_signed(p + 36, 4);
    v.crop_x = (int32_t)wf_signed(p + 40, 4);
    v.crop_y = (int32_t)wf_signed(p + 44, 4);
    v.crop_width = (int32_t)wf_signed(p + 48, 4);
    v.crop_height = (int32_t)wf_signed(p + 52, 4);
    v.transform = (uint16_t)wf_get(p + 56, 2);
    v.presentation_bits = (uint16_t)wf_get(p + 58, 2);
    *out = v;
    return 0;
}
int sophia_wf_projection_placement_encode(void *dst, size_t size, const struct sophia_wf_projection_placement *v)
{
    uint8_t p[60];
    if (!dst || !v || size < 60u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->surface_index, 4);
    wf_put(p + 4, (uint64_t)v->surface_generation, 4);
    wf_put(p + 8, (uint64_t)v->state_generation, 8);
    wf_put(p + 16, (uint64_t)v->x, 4);
    wf_put(p + 20, (uint64_t)v->y, 4);
    wf_put(p + 24, (uint64_t)v->width, 4);
    wf_put(p + 28, (uint64_t)v->height, 4);
    wf_put(p + 32, (uint64_t)v->requested_width, 4);
    wf_put(p + 36, (uint64_t)v->requested_height, 4);
    wf_put(p + 40, (uint64_t)v->crop_x, 4);
    wf_put(p + 44, (uint64_t)v->crop_y, 4);
    wf_put(p + 48, (uint64_t)v->crop_width, 4);
    wf_put(p + 52, (uint64_t)v->crop_height, 4);
    wf_put(p + 56, (uint64_t)v->transform, 2);
    wf_put(p + 58, (uint64_t)v->presentation_bits, 2);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_indicator_decode(const void *src, size_t size, struct sophia_wf_projection_indicator *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_indicator v;
    if (!src || !out) return -4;
    if (size != 64u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.slot = (uint32_t)wf_get(p + 8, 4);
    v.indicator = (uint64_t)wf_get(p + 12, 8);
    v.action = (uint64_t)wf_get(p + 20, 8);
    v.state_bits = (uint16_t)wf_get(p + 28, 2);
    v.label_len = (uint16_t)wf_get(p + 30, 2);
    memcpy(v.label, p + 32, 32);
    *out = v;
    return 0;
}
int sophia_wf_projection_indicator_encode(void *dst, size_t size, const struct sophia_wf_projection_indicator *v)
{
    uint8_t p[64];
    if (!dst || !v || size < 64u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->slot, 4);
    wf_put(p + 12, (uint64_t)v->indicator, 8);
    wf_put(p + 20, (uint64_t)v->action, 8);
    wf_put(p + 28, (uint64_t)v->state_bits, 2);
    wf_put(p + 30, (uint64_t)v->label_len, 2);
    memcpy(p + 32, v->label, 32);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_output_status_decode(const void *src, size_t size, struct sophia_wf_projection_output_status *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_output_status v;
    if (!src || !out) return -4;
    if (size != 48u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.focus_bits = (uint16_t)wf_get(p + 8, 2);
    v.layout_len = (uint16_t)wf_get(p + 10, 2);
    if (!wf_zero(p + 12, 4)) return -1;
    memcpy(v.layout, p + 16, 32);
    *out = v;
    return 0;
}
int sophia_wf_projection_output_status_encode(void *dst, size_t size, const struct sophia_wf_projection_output_status *v)
{
    uint8_t p[48];
    if (!dst || !v || size < 48u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->focus_bits, 2);
    wf_put(p + 10, (uint64_t)v->layout_len, 2);
    memcpy(p + 16, v->layout, 32);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_snapshot_surface_classification_decode(const void *src, size_t size, struct sophia_wf_snapshot_surface_classification *out)
{
    const uint8_t *p = src;
    struct sophia_wf_snapshot_surface_classification v;
    if (!src || !out) return -4;
    if (size != 16u) return -1;
    memset(&v, 0, sizeof(v));
    v.surface_index = (uint32_t)wf_get(p + 0, 4);
    v.surface_generation = (uint32_t)wf_get(p + 4, 4);
    v.classification = (uint64_t)wf_get(p + 8, 8);
    *out = v;
    return 0;
}
int sophia_wf_snapshot_surface_classification_encode(void *dst, size_t size, const struct sophia_wf_snapshot_surface_classification *v)
{
    uint8_t p[16];
    if (!dst || !v || size < 16u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->surface_index, 4);
    wf_put(p + 4, (uint64_t)v->surface_generation, 4);
    wf_put(p + 8, (uint64_t)v->classification, 8);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_launch_context_decode(const void *src, size_t size, struct sophia_wf_projection_launch_context *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_launch_context v;
    if (!src || !out) return -4;
    if (size != 24u) return -1;
    memset(&v, 0, sizeof(v));
    v.surface_index = (uint32_t)wf_get(p + 0, 4);
    v.surface_generation = (uint32_t)wf_get(p + 4, 4);
    v.epoch = (uint64_t)wf_get(p + 8, 8);
    v.token = (uint64_t)wf_get(p + 16, 8);
    *out = v;
    return 0;
}
int sophia_wf_projection_launch_context_encode(void *dst, size_t size, const struct sophia_wf_projection_launch_context *v)
{
    uint8_t p[24];
    if (!dst || !v || size < 24u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->surface_index, 4);
    wf_put(p + 4, (uint64_t)v->surface_generation, 4);
    wf_put(p + 8, (uint64_t)v->epoch, 8);
    wf_put(p + 16, (uint64_t)v->token, 8);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_output_launch_context_decode(const void *src, size_t size, struct sophia_wf_projection_output_launch_context *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_output_launch_context v;
    if (!src || !out) return -4;
    if (size != 32u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.generation = (uint64_t)wf_get(p + 8, 8);
    v.epoch = (uint64_t)wf_get(p + 16, 8);
    v.token = (uint64_t)wf_get(p + 24, 8);
    *out = v;
    return 0;
}
int sophia_wf_projection_output_launch_context_encode(void *dst, size_t size, const struct sophia_wf_projection_output_launch_context *v)
{
    uint8_t p[32];
    if (!dst || !v || size < 32u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->generation, 8);
    wf_put(p + 16, (uint64_t)v->epoch, 8);
    wf_put(p + 24, (uint64_t)v->token, 8);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_snapshot_launch_origin_decode(const void *src, size_t size, struct sophia_wf_snapshot_launch_origin *out)
{
    const uint8_t *p = src;
    struct sophia_wf_snapshot_launch_origin v;
    if (!src || !out) return -4;
    if (size != 24u) return -1;
    memset(&v, 0, sizeof(v));
    v.surface_index = (uint32_t)wf_get(p + 0, 4);
    v.surface_generation = (uint32_t)wf_get(p + 4, 4);
    v.epoch = (uint64_t)wf_get(p + 8, 8);
    v.token = (uint64_t)wf_get(p + 16, 8);
    *out = v;
    return 0;
}
int sophia_wf_snapshot_launch_origin_encode(void *dst, size_t size, const struct sophia_wf_snapshot_launch_origin *v)
{
    uint8_t p[24];
    if (!dst || !v || size < 24u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->surface_index, 4);
    wf_put(p + 4, (uint64_t)v->surface_generation, 4);
    wf_put(p + 8, (uint64_t)v->epoch, 8);
    wf_put(p + 16, (uint64_t)v->token, 8);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_snapshot_output_policy_key_decode(const void *src, size_t size, struct sophia_wf_snapshot_output_policy_key *out)
{
    const uint8_t *p = src;
    struct sophia_wf_snapshot_output_policy_key v;
    if (!src || !out) return -4;
    if (size != 24u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.generation = (uint64_t)wf_get(p + 8, 8);
    v.policy_key = (uint64_t)wf_get(p + 16, 8);
    *out = v;
    return 0;
}
int sophia_wf_snapshot_output_policy_key_encode(void *dst, size_t size, const struct sophia_wf_snapshot_output_policy_key *v)
{
    uint8_t p[24];
    if (!dst || !v || size < 24u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->generation, 8);
    wf_put(p + 16, (uint64_t)v->policy_key, 8);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_tab_group_decode(const void *src, size_t size, struct sophia_wf_projection_tab_group *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_tab_group v;
    if (!src || !out) return -4;
    if (size != 48u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.group = (uint64_t)wf_get(p + 8, 8);
    v.x = (int32_t)wf_signed(p + 16, 4);
    v.y = (int32_t)wf_signed(p + 20, 4);
    v.width = (int32_t)wf_signed(p + 24, 4);
    v.height = (int32_t)wf_signed(p + 28, 4);
    v.selected_index = (uint32_t)wf_get(p + 32, 4);
    v.selected_generation = (uint32_t)wf_get(p + 36, 4);
    v.member_count = (uint32_t)wf_get(p + 40, 4);
    v.focused = (uint32_t)wf_get(p + 44, 4);
    *out = v;
    return 0;
}
int sophia_wf_projection_tab_group_encode(void *dst, size_t size, const struct sophia_wf_projection_tab_group *v)
{
    uint8_t p[48];
    if (!dst || !v || size < 48u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->group, 8);
    wf_put(p + 16, (uint64_t)v->x, 4);
    wf_put(p + 20, (uint64_t)v->y, 4);
    wf_put(p + 24, (uint64_t)v->width, 4);
    wf_put(p + 28, (uint64_t)v->height, 4);
    wf_put(p + 32, (uint64_t)v->selected_index, 4);
    wf_put(p + 36, (uint64_t)v->selected_generation, 4);
    wf_put(p + 40, (uint64_t)v->member_count, 4);
    wf_put(p + 44, (uint64_t)v->focused, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_tab_member_decode(const void *src, size_t size, struct sophia_wf_projection_tab_member *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_tab_member v;
    if (!src || !out) return -4;
    if (size != 24u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.group = (uint64_t)wf_get(p + 8, 8);
    v.surface_index = (uint32_t)wf_get(p + 16, 4);
    v.surface_generation = (uint32_t)wf_get(p + 20, 4);
    *out = v;
    return 0;
}
int sophia_wf_projection_tab_member_encode(void *dst, size_t size, const struct sophia_wf_projection_tab_member *v)
{
    uint8_t p[24];
    if (!dst || !v || size < 24u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->group, 8);
    wf_put(p + 16, (uint64_t)v->surface_index, 4);
    wf_put(p + 20, (uint64_t)v->surface_generation, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_translation_group_decode(const void *src, size_t size, struct sophia_wf_projection_translation_group *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_translation_group v;
    if (!src || !out) return -4;
    if (size != 32u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.group = (uint64_t)wf_get(p + 8, 8);
    v.x = (int32_t)wf_signed(p + 16, 4);
    v.y = (int32_t)wf_signed(p + 20, 4);
    v.member_count = (uint32_t)wf_get(p + 24, 4);
    if (!wf_zero(p + 28, 4)) return -1;
    *out = v;
    return 0;
}
int sophia_wf_projection_translation_group_encode(void *dst, size_t size, const struct sophia_wf_projection_translation_group *v)
{
    uint8_t p[32];
    if (!dst || !v || size < 32u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->group, 8);
    wf_put(p + 16, (uint64_t)v->x, 4);
    wf_put(p + 20, (uint64_t)v->y, 4);
    wf_put(p + 24, (uint64_t)v->member_count, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_translation_member_decode(const void *src, size_t size, struct sophia_wf_projection_translation_member *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_translation_member v;
    if (!src || !out) return -4;
    if (size != 24u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.group = (uint64_t)wf_get(p + 8, 8);
    v.surface_index = (uint32_t)wf_get(p + 16, 4);
    v.surface_generation = (uint32_t)wf_get(p + 20, 4);
    *out = v;
    return 0;
}
int sophia_wf_projection_translation_member_encode(void *dst, size_t size, const struct sophia_wf_projection_translation_member *v)
{
    uint8_t p[24];
    if (!dst || !v || size < 24u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->group, 8);
    wf_put(p + 16, (uint64_t)v->surface_index, 4);
    wf_put(p + 20, (uint64_t)v->surface_generation, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_presentation_decode(const void *src, size_t size, struct sophia_wf_projection_presentation *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_presentation v;
    if (!src || !out) return -4;
    if (size != 32u) return -1;
    memset(&v, 0, sizeof(v));
    v.generation = (uint64_t)wf_get(p + 0, 8);
    v.keyboard_output = (uint64_t)wf_get(p + 8, 8);
    v.output_count = (uint16_t)wf_get(p + 16, 2);
    v.binding_count = (uint16_t)wf_get(p + 18, 2);
    v.instance_count = (uint32_t)wf_get(p + 20, 4);
    v.region_count = (uint32_t)wf_get(p + 24, 4);
    if (!wf_zero(p + 28, 4)) return -1;
    *out = v;
    return 0;
}
int sophia_wf_projection_presentation_encode(void *dst, size_t size, const struct sophia_wf_projection_presentation *v)
{
    uint8_t p[32];
    if (!dst || !v || size < 32u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->generation, 8);
    wf_put(p + 8, (uint64_t)v->keyboard_output, 8);
    wf_put(p + 16, (uint64_t)v->output_count, 2);
    wf_put(p + 18, (uint64_t)v->binding_count, 2);
    wf_put(p + 20, (uint64_t)v->instance_count, 4);
    wf_put(p + 24, (uint64_t)v->region_count, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_presentation_output_decode(const void *src, size_t size, struct sophia_wf_projection_presentation_output *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_presentation_output v;
    if (!src || !out) return -4;
    if (size != 40u) return -1;
    memset(&v, 0, sizeof(v));
    v.output = (uint64_t)wf_get(p + 0, 8);
    v.generation = (uint64_t)wf_get(p + 8, 8);
    v.x = (int32_t)wf_signed(p + 16, 4);
    v.y = (int32_t)wf_signed(p + 20, 4);
    v.width = (int32_t)wf_signed(p + 24, 4);
    v.height = (int32_t)wf_signed(p + 28, 4);
    v.mode = (uint16_t)wf_get(p + 32, 2);
    if (!wf_zero(p + 34, 2)) return -1;
    if (!wf_zero(p + 36, 4)) return -1;
    *out = v;
    return 0;
}
int sophia_wf_projection_presentation_output_encode(void *dst, size_t size, const struct sophia_wf_projection_presentation_output *v)
{
    uint8_t p[40];
    if (!dst || !v || size < 40u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->output, 8);
    wf_put(p + 8, (uint64_t)v->generation, 8);
    wf_put(p + 16, (uint64_t)v->x, 4);
    wf_put(p + 20, (uint64_t)v->y, 4);
    wf_put(p + 24, (uint64_t)v->width, 4);
    wf_put(p + 28, (uint64_t)v->height, 4);
    wf_put(p + 32, (uint64_t)v->mode, 2);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_surface_instance_decode(const void *src, size_t size, struct sophia_wf_projection_surface_instance *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_surface_instance v;
    if (!src || !out) return -4;
    if (size != 80u) return -1;
    memset(&v, 0, sizeof(v));
    v.id = (uint64_t)wf_get(p + 0, 8);
    v.generation = (uint64_t)wf_get(p + 8, 8);
    v.output = (uint64_t)wf_get(p + 16, 8);
    v.source_index = (uint32_t)wf_get(p + 24, 4);
    v.source_generation = (uint32_t)wf_get(p + 28, 4);
    v.x = (int32_t)wf_signed(p + 32, 4);
    v.y = (int32_t)wf_signed(p + 36, 4);
    v.width = (int32_t)wf_signed(p + 40, 4);
    v.height = (int32_t)wf_signed(p + 44, 4);
    v.clip_x = (int32_t)wf_signed(p + 48, 4);
    v.clip_y = (int32_t)wf_signed(p + 52, 4);
    v.clip_width = (int32_t)wf_signed(p + 56, 4);
    v.clip_height = (int32_t)wf_signed(p + 60, 4);
    v.opacity_millis = (uint16_t)wf_get(p + 64, 2);
    v.z_index = (uint16_t)wf_get(p + 66, 2);
    if (!wf_zero(p + 68, 4)) return -1;
    v.action = (uint64_t)wf_get(p + 72, 8);
    *out = v;
    return 0;
}
int sophia_wf_projection_surface_instance_encode(void *dst, size_t size, const struct sophia_wf_projection_surface_instance *v)
{
    uint8_t p[80];
    if (!dst || !v || size < 80u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->id, 8);
    wf_put(p + 8, (uint64_t)v->generation, 8);
    wf_put(p + 16, (uint64_t)v->output, 8);
    wf_put(p + 24, (uint64_t)v->source_index, 4);
    wf_put(p + 28, (uint64_t)v->source_generation, 4);
    wf_put(p + 32, (uint64_t)v->x, 4);
    wf_put(p + 36, (uint64_t)v->y, 4);
    wf_put(p + 40, (uint64_t)v->width, 4);
    wf_put(p + 44, (uint64_t)v->height, 4);
    wf_put(p + 48, (uint64_t)v->clip_x, 4);
    wf_put(p + 52, (uint64_t)v->clip_y, 4);
    wf_put(p + 56, (uint64_t)v->clip_width, 4);
    wf_put(p + 60, (uint64_t)v->clip_height, 4);
    wf_put(p + 64, (uint64_t)v->opacity_millis, 2);
    wf_put(p + 66, (uint64_t)v->z_index, 2);
    wf_put(p + 72, (uint64_t)v->action, 8);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_presentation_region_decode(const void *src, size_t size, struct sophia_wf_projection_presentation_region *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_presentation_region v;
    if (!src || !out) return -4;
    if (size != 72u) return -1;
    memset(&v, 0, sizeof(v));
    v.id = (uint64_t)wf_get(p + 0, 8);
    v.generation = (uint64_t)wf_get(p + 8, 8);
    v.output = (uint64_t)wf_get(p + 16, 8);
    v.x = (int32_t)wf_signed(p + 24, 4);
    v.y = (int32_t)wf_signed(p + 28, 4);
    v.width = (int32_t)wf_signed(p + 32, 4);
    v.height = (int32_t)wf_signed(p + 36, 4);
    v.clip_x = (int32_t)wf_signed(p + 40, 4);
    v.clip_y = (int32_t)wf_signed(p + 44, 4);
    v.clip_width = (int32_t)wf_signed(p + 48, 4);
    v.clip_height = (int32_t)wf_signed(p + 52, 4);
    v.z_index = (uint16_t)wf_get(p + 56, 2);
    v.role = (uint16_t)wf_get(p + 58, 2);
    if (!wf_zero(p + 60, 4)) return -1;
    v.action = (uint64_t)wf_get(p + 64, 8);
    *out = v;
    return 0;
}
int sophia_wf_projection_presentation_region_encode(void *dst, size_t size, const struct sophia_wf_projection_presentation_region *v)
{
    uint8_t p[72];
    if (!dst || !v || size < 72u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->id, 8);
    wf_put(p + 8, (uint64_t)v->generation, 8);
    wf_put(p + 16, (uint64_t)v->output, 8);
    wf_put(p + 24, (uint64_t)v->x, 4);
    wf_put(p + 28, (uint64_t)v->y, 4);
    wf_put(p + 32, (uint64_t)v->width, 4);
    wf_put(p + 36, (uint64_t)v->height, 4);
    wf_put(p + 40, (uint64_t)v->clip_x, 4);
    wf_put(p + 44, (uint64_t)v->clip_y, 4);
    wf_put(p + 48, (uint64_t)v->clip_width, 4);
    wf_put(p + 52, (uint64_t)v->clip_height, 4);
    wf_put(p + 56, (uint64_t)v->z_index, 2);
    wf_put(p + 58, (uint64_t)v->role, 2);
    wf_put(p + 64, (uint64_t)v->action, 8);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int sophia_wf_projection_presentation_binding_decode(const void *src, size_t size, struct sophia_wf_projection_presentation_binding *out)
{
    const uint8_t *p = src;
    struct sophia_wf_projection_presentation_binding v;
    if (!src || !out) return -4;
    if (size != 16u) return -1;
    memset(&v, 0, sizeof(v));
    v.action = (uint64_t)wf_get(p + 0, 8);
    v.keycode = (uint32_t)wf_get(p + 8, 4);
    v.modifiers = (uint32_t)wf_get(p + 12, 4);
    *out = v;
    return 0;
}
int sophia_wf_projection_presentation_binding_encode(void *dst, size_t size, const struct sophia_wf_projection_presentation_binding *v)
{
    uint8_t p[16];
    if (!dst || !v || size < 16u) return -4;
    memset(p, 0, sizeof(p));
    wf_put(p + 0, (uint64_t)v->action, 8);
    wf_put(p + 8, (uint64_t)v->keycode, 4);
    wf_put(p + 12, (uint64_t)v->modifiers, 4);
    memcpy(dst, p, sizeof(p));
    return 0;
}
int wf_row_layout(uint16_t family, uint16_t kind, size_t *width,
                  uint32_t *maximum, uint64_t *capabilities)
{
    if (family == SOPHIA_WF_SNAPSHOT && kind == 1u) {
        *width = 56; *maximum = 16;
        *capabilities = 0;
        return 0;
    }
    if (family == SOPHIA_WF_SNAPSHOT && kind == 2u) {
        *width = 80; *maximum = 1024;
        *capabilities = 0;
        return 0;
    }
    if ((family == SOPHIA_WF_SNAPSHOT || family == SOPHIA_WF_CONFIGURATION) && kind == 3u) {
        *width = 140; *maximum = 256;
        *capabilities = SOPHIA_WF_CAP_ACTIONS;
        return 0;
    }
    if (family == SOPHIA_WF_SNAPSHOT && kind == 4u) {
        *width = 12; *maximum = 256;
        *capabilities = SOPHIA_WF_CAP_SESSION_OPERATIONS;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 1u) {
        *width = 24; *maximum = 16;
        *capabilities = 0;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 2u) {
        *width = 60; *maximum = 1024;
        *capabilities = 0;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 3u) {
        *width = 64; *maximum = 256;
        *capabilities = SOPHIA_WF_CAP_INDICATORS;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 4u) {
        *width = 48; *maximum = 16;
        *capabilities = SOPHIA_WF_CAP_INDICATORS;
        return 0;
    }
    if (family == SOPHIA_WF_SNAPSHOT && kind == 65280u) {
        *width = 16; *maximum = 1024;
        *capabilities = SOPHIA_WF_CAP_LAUNCH_PLACEMENT;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65285u) {
        *width = 24; *maximum = 1024;
        *capabilities = SOPHIA_WF_CAP_LAUNCH_ORIGIN;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65288u) {
        *width = 32; *maximum = 16;
        *capabilities = SOPHIA_WF_CAP_OUTPUT_LAUNCH_CONTEXT | SOPHIA_WF_CAP_LAUNCH_ORIGIN;
        return 0;
    }
    if (family == SOPHIA_WF_SNAPSHOT && kind == 65286u) {
        *width = 24; *maximum = 1024;
        *capabilities = SOPHIA_WF_CAP_LAUNCH_ORIGIN;
        return 0;
    }
    if (family == SOPHIA_WF_SNAPSHOT && kind == 65287u) {
        *width = 24; *maximum = 16;
        *capabilities = SOPHIA_WF_CAP_OUTPUT_POLICY_KEYS;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65281u) {
        *width = 48; *maximum = 1024;
        *capabilities = SOPHIA_WF_CAP_TAB_GROUPS;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65282u) {
        *width = 24; *maximum = 2048;
        *capabilities = SOPHIA_WF_CAP_TAB_GROUPS;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65283u) {
        *width = 32; *maximum = 16;
        *capabilities = SOPHIA_WF_CAP_TRANSLATION_GROUPS;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65284u) {
        *width = 24; *maximum = 1024;
        *capabilities = SOPHIA_WF_CAP_TRANSLATION_GROUPS;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65289u) {
        *width = 32; *maximum = 1;
        *capabilities = SOPHIA_WF_CAP_SURFACE_INSTANCES;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65290u) {
        *width = 40; *maximum = 16;
        *capabilities = SOPHIA_WF_CAP_SURFACE_INSTANCES;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65291u) {
        *width = 80; *maximum = 1024;
        *capabilities = SOPHIA_WF_CAP_SURFACE_INSTANCES;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65292u) {
        *width = 72; *maximum = 1024;
        *capabilities = SOPHIA_WF_CAP_SURFACE_INSTANCES;
        return 0;
    }
    if (family == SOPHIA_WF_PROJECTION && kind == 65293u) {
        *width = 16; *maximum = 256;
        *capabilities = SOPHIA_WF_CAP_PRESENTATION_ACTIONS | SOPHIA_WF_CAP_ACTIONS | SOPHIA_WF_CAP_SURFACE_INSTANCES;
        return 0;
    }
    return -1;
}
int wf_row_reserved(uint16_t family, uint16_t kind, const uint8_t *p)
{
    if (family == SOPHIA_WF_PROJECTION && kind == 1u)
        return wf_zero(p + 20, 4) ? 0 : -1;
    if (family == SOPHIA_WF_PROJECTION && kind == 4u)
        return wf_zero(p + 12, 4) ? 0 : -1;
    if (family == SOPHIA_WF_PROJECTION && kind == 65283u)
        return wf_zero(p + 28, 4) ? 0 : -1;
    if (family == SOPHIA_WF_PROJECTION && kind == 65289u)
        return wf_zero(p + 28, 4) ? 0 : -1;
    if (family == SOPHIA_WF_PROJECTION && kind == 65290u)
        return wf_zero(p + 34, 2) && wf_zero(p + 36, 4) ? 0 : -1;
    if (family == SOPHIA_WF_PROJECTION && kind == 65291u)
        return wf_zero(p + 68, 4) ? 0 : -1;
    if (family == SOPHIA_WF_PROJECTION && kind == 65292u)
        return wf_zero(p + 60, 4) ? 0 : -1;
    return 0;
}
