/* KDL-derived internal field functions. */
int sf_check_content_output_facts_entry(const struct sophia_sf_content_output_facts_entry *v);
void sf_put_content_output_facts_entry(uint8_t *b,
                                       const struct sophia_sf_content_output_facts_entry *v);
int sf_take_content_output_facts_entry(const uint8_t *b,
                                       struct sophia_sf_content_output_facts_entry *v);
int sf_check_content_surface(const struct sophia_sf_content_surface *v);
void sf_put_content_surface(uint8_t *b, const struct sophia_sf_content_surface *v);
int sf_take_content_surface(const uint8_t *b, struct sophia_sf_content_surface *v);
int sf_check_content_placement(const struct sophia_sf_content_placement *v);
void sf_put_content_placement(uint8_t *b, const struct sophia_sf_content_placement *v);
int sf_take_content_placement(const uint8_t *b, struct sophia_sf_content_placement *v);
int sf_check_content_target(const struct sophia_sf_content_target *v);
void sf_put_content_target(uint8_t *b, const struct sophia_sf_content_target *v);
int sf_take_content_target(const uint8_t *b, struct sophia_sf_content_target *v);
int sf_check_limits(const struct sophia_sf_limits *v);
void sf_put_limits(uint8_t *b, const struct sophia_sf_limits *v);
int sf_take_limits(const uint8_t *b, struct sophia_sf_limits *v);
int sf_check_outputs(const struct sophia_sf_outputs *v);
void sf_put_outputs(uint8_t *b, const struct sophia_sf_outputs *v);
int sf_take_outputs(const uint8_t *b, struct sophia_sf_outputs *v);
int sf_check_negotiate(const struct sophia_sf_negotiate *v);
void sf_put_negotiate(uint8_t *b, const struct sophia_sf_negotiate *v);
int sf_take_negotiate(const uint8_t *b, struct sophia_sf_negotiate *v);
int sf_check_negotiated(const struct sophia_sf_negotiated *v);
void sf_put_negotiated(uint8_t *b, const struct sophia_sf_negotiated *v);
int sf_take_negotiated(const uint8_t *b, struct sophia_sf_negotiated *v);
int sf_check_refused(const struct sophia_sf_refused *v);
void sf_put_refused(uint8_t *b, const struct sophia_sf_refused *v);
int sf_take_refused(const uint8_t *b, struct sophia_sf_refused *v);
int sf_check_submitted(const struct sophia_sf_submitted *v);
void sf_put_submitted(uint8_t *b, const struct sophia_sf_submitted *v);
int sf_take_submitted(const uint8_t *b, struct sophia_sf_submitted *v);
int sf_check_object_published(const struct sophia_sf_object_published *v);
void sf_put_object_published(uint8_t *b, const struct sophia_sf_object_published *v);
int sf_take_object_published(const uint8_t *b, struct sophia_sf_object_published *v);
int sf_check_allocation_request(const struct sophia_sf_allocation_request *v);
void sf_put_allocation_request(uint8_t *b, const struct sophia_sf_allocation_request *v);
int sf_take_allocation_request(const uint8_t *b, struct sophia_sf_allocation_request *v);
int sf_check_allocation_result(const struct sophia_sf_allocation_result *v);
void sf_put_allocation_result(uint8_t *b, const struct sophia_sf_allocation_result *v);
int sf_take_allocation_result(const uint8_t *b, struct sophia_sf_allocation_result *v);
int sf_check_resource_begin(const struct sophia_sf_resource_begin *v);
void sf_put_resource_begin(uint8_t *b, const struct sophia_sf_resource_begin *v);
int sf_take_resource_begin(const uint8_t *b, struct sophia_sf_resource_begin *v);
int sf_check_resource_end(const struct sophia_sf_resource_end *v);
void sf_put_resource_end(uint8_t *b, const struct sophia_sf_resource_end *v);
int sf_take_resource_end(const uint8_t *b, struct sophia_sf_resource_end *v);
int sf_check_resource_cancel(const struct sophia_sf_resource_cancel *v);
void sf_put_resource_cancel(uint8_t *b, const struct sophia_sf_resource_cancel *v);
int sf_take_resource_cancel(const uint8_t *b, struct sophia_sf_resource_cancel *v);
int sf_check_resource_retire(const struct sophia_sf_resource_retire *v);
void sf_put_resource_retire(uint8_t *b, const struct sophia_sf_resource_retire *v);
int sf_take_resource_retire(const uint8_t *b, struct sophia_sf_resource_retire *v);
int sf_check_resource_status(const struct sophia_sf_resource_status *v);
void sf_put_resource_status(uint8_t *b, const struct sophia_sf_resource_status *v);
int sf_take_resource_status(const uint8_t *b, struct sophia_sf_resource_status *v);
int sf_check_resource_released(const struct sophia_sf_resource_released *v);
void sf_put_resource_released(uint8_t *b, const struct sophia_sf_resource_released *v);
int sf_take_resource_released(const uint8_t *b, struct sophia_sf_resource_released *v);
int sf_check_candidate(const struct sophia_sf_candidate *v);
void sf_put_candidate(uint8_t *b, const struct sophia_sf_candidate *v);
int sf_take_candidate(const uint8_t *b, struct sophia_sf_candidate *v);
int sf_check_frame_demand(const struct sophia_sf_frame_demand *v);
void sf_put_frame_demand(uint8_t *b, const struct sophia_sf_frame_demand *v);
int sf_take_frame_demand(const uint8_t *b, struct sophia_sf_frame_demand *v);
int sf_check_frame_demand_cancel(const struct sophia_sf_frame_demand_cancel *v);
void sf_put_frame_demand_cancel(uint8_t *b, const struct sophia_sf_frame_demand_cancel *v);
int sf_take_frame_demand_cancel(const uint8_t *b, struct sophia_sf_frame_demand_cancel *v);
int sf_check_frame_permit(const struct sophia_sf_frame_permit *v);
void sf_put_frame_permit(uint8_t *b, const struct sophia_sf_frame_permit *v);
int sf_take_frame_permit(const uint8_t *b, struct sophia_sf_frame_permit *v);
int sf_check_action(const struct sophia_sf_action *v);
void sf_put_action(uint8_t *b, const struct sophia_sf_action *v);
int sf_take_action(const uint8_t *b, struct sophia_sf_action *v);
int sf_check_action_ack(const struct sophia_sf_action_ack *v);
void sf_put_action_ack(uint8_t *b, const struct sophia_sf_action_ack *v);
int sf_take_action_ack(const uint8_t *b, struct sophia_sf_action_ack *v);
int sf_check_candidate_outcome(const struct sophia_sf_candidate_outcome *v);
void sf_put_candidate_outcome(uint8_t *b, const struct sophia_sf_candidate_outcome *v);
int sf_take_candidate_outcome(const uint8_t *b, struct sophia_sf_candidate_outcome *v);
