#!/usr/bin/env python3
"""Generate neutral fixed WM rows from the pinned schema; never IPC frames."""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "spec/sophia-wm-v1.kdl"


def snake(value):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()


def main():
    text = SCHEMA.read_text()
    rows = []
    for match in re.finditer(
        r'(?:extension-)?record "(\w+)" transfer="(\w+)" kind=(\d+)'
        r'(?: gate="(\w+)")? max=(\d+) \{([^}]+)\}', text
    ):
        name, family, kind, gate, maximum, body = match.groups()
        fields = []
        offset = 0
        for line in body.splitlines():
            if not line.strip():
                continue
            field = re.fullmatch(
                r'\s*field "(\w+)" type="(u8|u16|u32|u64|i32)"'
                r'(?: count=(\d+))?(?: reserved=#true)? sample=.+', line
            )
            if not field:
                raise ValueError(f"unsupported row field: {line}")
            key, typ, count = field.groups()
            width = int(typ[1:]) // 8
            count = int(count or 1)
            fields.append((key, typ, width, count, offset))
            offset += width * count
        rows.append((snake(name), family, int(kind), gate, int(maximum), offset, fields))
    if len(rows) != 22:
        raise ValueError("review changed WM row inventory before regeneration")
    h = ["/* Generated by tools/generate_wm_rows.py from spec/sophia-wm-v1.kdl. */",
         "#ifndef SOPHIA_WM_RECORDS_H", "#define SOPHIA_WM_RECORDS_H",
         "#include <stddef.h>", "#include <stdint.h>"]
    for name, bit in re.findall(r'capability "(\w+)" bit=(\d+)', text):
        h.append(f"#define SOPHIA_WF_CAP_{name.upper()} (UINT64_C(1) << {bit})")
    h += ["/* Fixed rows only; no socket headers or transfer framing.",
          " * Decode and encode check width and reserved bytes. Complete file-record",
          " * validation additionally checks sections and negotiated capabilities.",
          " * Outputs are unchanged on error. Return 0, -1 invalid, -4 argument/space.",
          " * Destination must not overlap the value or its source bytes. */"]
    c = ["/* Generated by tools/generate_wm_rows.py from spec/sophia-wm-v1.kdl. */",
         '#include "internal.h"']
    types = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t",
             "u64": "uint64_t", "i32": "int32_t"}
    for name, family, kind, gate, maximum, size, fields in rows:
        base = "sophia_wf_" + name
        h += [f"#define SOPHIA_WF_{name.upper()}_BYTES {size}u",
              f"struct {base} {{"]
        for key, typ, width, count, offset in fields:
            if not key.startswith("reserved"):
                suffix = f"[{count}]" if count > 1 else ""
                h.append(f"    {types[typ]} {key}{suffix};")
        h += ["};", f"int {base}_decode(const void *, size_t, struct {base} *);",
              f"int {base}_encode(void *, size_t, const struct {base} *);"]
        c += [f"int {base}_decode(const void *src, size_t size, struct {base} *out)",
              "{", "    const uint8_t *p = src;", f"    struct {base} v;",
              "    if (!src || !out) return -4;", f"    if (size != {size}u) return -1;",
              "    memset(&v, 0, sizeof(v));"]
        for key, typ, width, count, offset in fields:
            if key.startswith("reserved"):
                c.append(f"    if (!wf_zero(p + {offset}, {width * count})) return -1;")
            elif count > 1:
                c.append(f"    memcpy(v.{key}, p + {offset}, {count});")
            else:
                getter = "wf_signed" if typ == "i32" else "wf_get"
                c.append(f"    v.{key} = ({types[typ]}){getter}(p + {offset}, {width});")
        c += ["    *out = v;", "    return 0;", "}",
              f"int {base}_encode(void *dst, size_t size, const struct {base} *v)",
              "{", f"    uint8_t p[{size}];",
              f"    if (!dst || !v || size < {size}u) return -4;",
              "    memset(p, 0, sizeof(p));"]
        for key, typ, width, count, offset in fields:
            if key.startswith("reserved"):
                continue
            if count > 1:
                c.append(f"    memcpy(p + {offset}, v->{key}, {count});")
            else:
                c.append(f"    wf_put(p + {offset}, (uint64_t)v->{key}, {width});")
        c += ["    memcpy(dst, p, sizeof(p));", "    return 0;", "}"]
    c += ["int wf_row_layout(uint16_t family, uint16_t kind, size_t *width,",
          "                  uint32_t *maximum, uint64_t *capabilities)", "{"]
    families = {"snapshot": "SOPHIA_WF_SNAPSHOT", "projection": "SOPHIA_WF_PROJECTION"}
    caps = {"snapshot_action": "ACTIONS", "snapshot_session_operation": "SESSION_OPERATIONS",
            "projection_indicator": "INDICATORS", "projection_output_status": "INDICATORS"}
    for name, family, kind, gate, maximum, size, fields in rows:
        cap = gate.upper() if gate else caps.get(name)
        cap_expr = "SOPHIA_WF_CAP_" + cap if cap else "0"
        if cap == "OUTPUT_LAUNCH_CONTEXT":
            cap_expr += " | SOPHIA_WF_CAP_LAUNCH_ORIGIN"
        if cap == "PRESENTATION_ACTIONS":
            cap_expr += " | SOPHIA_WF_CAP_ACTIONS | SOPHIA_WF_CAP_SURFACE_INSTANCES"
        cond = f"family == {families[family]} && kind == {kind}u"
        if name == "snapshot_action":
            cond = f"(family == SOPHIA_WF_SNAPSHOT || family == SOPHIA_WF_CONFIGURATION) && kind == {kind}u"
        c += [f"    if ({cond}) {{", f"        *width = {size}; *maximum = {maximum};",
              f"        *capabilities = {cap_expr};", "        return 0;", "    }"]
    c += ["    return -1;", "}",
          "int wf_row_reserved(uint16_t family, uint16_t kind, const uint8_t *p)", "{"]
    for name, family, kind, gate, maximum, size, fields in rows:
        reserved = [(offset, width * count) for key, typ, width, count, offset in fields
                    if key.startswith("reserved")]
        if reserved:
            cond = " && ".join(f"wf_zero(p + {offset}, {width})" for offset, width in reserved)
            c += [f"    if (family == {families[family]} && kind == {kind}u)",
                  f"        return {cond} ? 0 : -1;"]
    c += ["    return 0;", "}"]
    h += ["#endif", ""]
    (ROOT / "src/wm_files").mkdir(exist_ok=True)
    (ROOT / "src/sophia_wm_records.h").write_text("\n".join(h))
    (ROOT / "src/wm_files/rows.c").write_text("\n".join(c) + "\n")


if __name__ == "__main__":
    main()
