/* @generated by sophia-policy-protocol-gen; do not edit. */
#include "sophia_wm_v1.h"

#define SOPHIA_IPC_MAGIC UINT32_C(0x48504f53)
#define SOPHIA_IPC_FRAME_VERSION 1u
#define SOPHIA_IPC_HEADER_LEN 24u
#define SOPHIA_IPC_MAX_PAYLOAD_LEN 65536u

static void put_u16(uint8_t *out, uint16_t value) {
    out[0] = (uint8_t)value;
    out[1] = (uint8_t)(value >> 8);
}

static void put_u32(uint8_t *out, uint32_t value) {
    for (size_t index = 0; index < 4; ++index) out[index] = (uint8_t)(value >> (8 * index));
}

static void put_u64(uint8_t *out, uint64_t value) {
    for (size_t index = 0; index < 8; ++index) out[index] = (uint8_t)(value >> (8 * index));
}

static void put_i32(uint8_t *out, int32_t value) {
    put_u32(out, (uint32_t)value);
}

static uint16_t get_u16(const uint8_t *in) {
    return (uint16_t)in[0] | ((uint16_t)in[1] << 8);
}

static uint32_t get_u32(const uint8_t *in) {
    uint32_t value = 0;
    for (size_t index = 0; index < 4; ++index) value |= ((uint32_t)in[index]) << (8 * index);
    return value;
}

static uint64_t get_u64(const uint8_t *in) {
    uint64_t value = 0;
    for (size_t index = 0; index < 8; ++index) value |= ((uint64_t)in[index]) << (8 * index);
    return value;
}

static int32_t get_i32(const uint8_t *in) {
    return (int32_t)get_u32(in);
}

static void put_bytes(uint8_t *out, const uint8_t *value, size_t len) {
    for (size_t index = 0; index < len; ++index) out[index] = value[index];
}

static void get_bytes(const uint8_t *in, uint8_t *value, size_t len) {
    for (size_t index = 0; index < len; ++index) value[index] = in[index];
}

static enum sophia_wm_v1_status write_header(uint16_t kind, uint64_t transaction, size_t payload_len, uint8_t *out, size_t capacity, size_t *written) {
    if (payload_len > SOPHIA_IPC_MAX_PAYLOAD_LEN) return SOPHIA_WM_V1_PAYLOAD_TOO_LARGE;
    if (capacity < SOPHIA_IPC_HEADER_LEN + payload_len) return SOPHIA_WM_V1_TRUNCATED;
    put_u32(out, SOPHIA_IPC_MAGIC);
    put_u16(out + 4, SOPHIA_IPC_FRAME_VERSION);
    put_u16(out + 6, kind);
    put_u64(out + 8, transaction);
    put_u32(out + 16, (uint32_t)payload_len);
    put_u32(out + 20, 0);
    *written = SOPHIA_IPC_HEADER_LEN + payload_len;
    return SOPHIA_WM_V1_OK;
}

static enum sophia_wm_v1_status read_header(const uint8_t *frame, size_t frame_len, uint16_t expected_kind, uint64_t *transaction, size_t *payload_len) {
    if (frame_len < SOPHIA_IPC_HEADER_LEN) return SOPHIA_WM_V1_TRUNCATED;
    if (get_u32(frame) != SOPHIA_IPC_MAGIC) return SOPHIA_WM_V1_BAD_MAGIC;
    if (get_u16(frame + 4) != SOPHIA_IPC_FRAME_VERSION) return SOPHIA_WM_V1_UNSUPPORTED_FRAME_VERSION;
    if (get_u16(frame + 6) != expected_kind) return SOPHIA_WM_V1_WRONG_MESSAGE_KIND;
    if (get_u32(frame + 20) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    *transaction = get_u64(frame + 8);
    *payload_len = get_u32(frame + 16);
    if (*payload_len > SOPHIA_IPC_MAX_PAYLOAD_LEN) return SOPHIA_WM_V1_PAYLOAD_TOO_LARGE;
    if (frame_len < SOPHIA_IPC_HEADER_LEN + *payload_len) return SOPHIA_WM_V1_TRUNCATED;
    if (frame_len > SOPHIA_IPC_HEADER_LEN + *payload_len) return SOPHIA_WM_V1_TRAILING_BYTES;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_output_record(const struct sophia_wm_v1_snapshot_output_record *record, uint8_t *out, size_t capacity) {
    if (capacity < 56u) return SOPHIA_WM_V1_TRUNCATED;
    put_u64(out + 0, record->output);
    put_u64(out + 8, record->generation);
    put_u32(out + 16, record->focus_index);
    put_u32(out + 20, record->focus_generation);
    put_i32(out + 24, record->x);
    put_i32(out + 28, record->y);
    put_i32(out + 32, record->width);
    put_i32(out + 36, record->height);
    put_i32(out + 40, record->work_x);
    put_i32(out + 44, record->work_y);
    put_i32(out + 48, record->work_width);
    put_i32(out + 52, record->work_height);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_output_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_snapshot_output_record *record) {
    if (data_len % 56u != 0) return data_len < 56u ? SOPHIA_WM_V1_TRUNCATED : SOPHIA_WM_V1_TRAILING_BYTES;
    size_t count = data_len / 56u;
    if (count > 16u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    if (index >= count) return SOPHIA_WM_V1_TRUNCATED;
    const uint8_t *cursor = data + index * 56u;
    record->output = get_u64(cursor + 0);
    record->generation = get_u64(cursor + 8);
    record->focus_index = get_u32(cursor + 16);
    record->focus_generation = get_u32(cursor + 20);
    record->x = get_i32(cursor + 24);
    record->y = get_i32(cursor + 28);
    record->width = get_i32(cursor + 32);
    record->height = get_i32(cursor + 36);
    record->work_x = get_i32(cursor + 40);
    record->work_y = get_i32(cursor + 44);
    record->work_width = get_i32(cursor + 48);
    record->work_height = get_i32(cursor + 52);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_surface_record(const struct sophia_wm_v1_snapshot_surface_record *record, uint8_t *out, size_t capacity) {
    if (capacity < 80u) return SOPHIA_WM_V1_TRUNCATED;
    put_u32(out + 0, record->surface_index);
    put_u32(out + 4, record->surface_generation);
    put_u64(out + 8, record->state_generation);
    put_u64(out + 16, record->current_output);
    put_u16(out + 24, record->capability_bits);
    put_u16(out + 26, record->kind);
    put_u16(out + 28, record->request_state_bits);
    put_u16(out + 30, record->current_state_bits);
    put_u32(out + 32, record->transient_index);
    put_u32(out + 36, record->transient_generation);
    put_i32(out + 40, record->x);
    put_i32(out + 44, record->y);
    put_i32(out + 48, record->width);
    put_i32(out + 52, record->height);
    put_i32(out + 56, record->min_width);
    put_i32(out + 60, record->min_height);
    put_i32(out + 64, record->max_width);
    put_i32(out + 68, record->max_height);
    put_i32(out + 72, record->exact_width);
    put_i32(out + 76, record->exact_height);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_surface_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_snapshot_surface_record *record) {
    if (data_len % 80u != 0) return data_len < 80u ? SOPHIA_WM_V1_TRUNCATED : SOPHIA_WM_V1_TRAILING_BYTES;
    size_t count = data_len / 80u;
    if (count > 1024u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    if (index >= count) return SOPHIA_WM_V1_TRUNCATED;
    const uint8_t *cursor = data + index * 80u;
    record->surface_index = get_u32(cursor + 0);
    record->surface_generation = get_u32(cursor + 4);
    record->state_generation = get_u64(cursor + 8);
    record->current_output = get_u64(cursor + 16);
    record->capability_bits = get_u16(cursor + 24);
    record->kind = get_u16(cursor + 26);
    record->request_state_bits = get_u16(cursor + 28);
    record->current_state_bits = get_u16(cursor + 30);
    record->transient_index = get_u32(cursor + 32);
    record->transient_generation = get_u32(cursor + 36);
    record->x = get_i32(cursor + 40);
    record->y = get_i32(cursor + 44);
    record->width = get_i32(cursor + 48);
    record->height = get_i32(cursor + 52);
    record->min_width = get_i32(cursor + 56);
    record->min_height = get_i32(cursor + 60);
    record->max_width = get_i32(cursor + 64);
    record->max_height = get_i32(cursor + 68);
    record->exact_width = get_i32(cursor + 72);
    record->exact_height = get_i32(cursor + 76);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_action_record(const struct sophia_wm_v1_snapshot_action_record *record, uint8_t *out, size_t capacity) {
    if (capacity < 140u) return SOPHIA_WM_V1_TRUNCATED;
    put_u64(out + 0, record->action);
    put_u16(out + 8, record->session_operation_slot);
    put_u16(out + 10, record->name_len);
    put_bytes(out + 12, record->name, 128u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_action_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_snapshot_action_record *record) {
    if (data_len % 140u != 0) return data_len < 140u ? SOPHIA_WM_V1_TRUNCATED : SOPHIA_WM_V1_TRAILING_BYTES;
    size_t count = data_len / 140u;
    if (count > 256u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    if (index >= count) return SOPHIA_WM_V1_TRUNCATED;
    const uint8_t *cursor = data + index * 140u;
    record->action = get_u64(cursor + 0);
    record->session_operation_slot = get_u16(cursor + 8);
    record->name_len = get_u16(cursor + 10);
    get_bytes(cursor + 12, record->name, 128u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_session_operation_record(const struct sophia_wm_v1_snapshot_session_operation_record *record, uint8_t *out, size_t capacity) {
    if (capacity < 12u) return SOPHIA_WM_V1_TRUNCATED;
    put_u64(out + 0, record->operation);
    put_u16(out + 8, record->slot);
    put_u16(out + 10, record->target_bits);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_session_operation_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_snapshot_session_operation_record *record) {
    if (data_len % 12u != 0) return data_len < 12u ? SOPHIA_WM_V1_TRUNCATED : SOPHIA_WM_V1_TRAILING_BYTES;
    size_t count = data_len / 12u;
    if (count > 256u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    if (index >= count) return SOPHIA_WM_V1_TRUNCATED;
    const uint8_t *cursor = data + index * 12u;
    record->operation = get_u64(cursor + 0);
    record->slot = get_u16(cursor + 8);
    record->target_bits = get_u16(cursor + 10);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_output_record(const struct sophia_wm_v1_projection_output_record *record, uint8_t *out, size_t capacity) {
    if (capacity < 24u) return SOPHIA_WM_V1_TRUNCATED;
    put_u64(out + 0, record->output);
    put_u32(out + 8, record->placement_count);
    put_u32(out + 12, record->focus_index);
    put_u32(out + 16, record->focus_generation);
    put_u32(out + 20, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_output_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_projection_output_record *record) {
    if (data_len % 24u != 0) return data_len < 24u ? SOPHIA_WM_V1_TRUNCATED : SOPHIA_WM_V1_TRAILING_BYTES;
    size_t count = data_len / 24u;
    if (count > 16u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    if (index >= count) return SOPHIA_WM_V1_TRUNCATED;
    const uint8_t *cursor = data + index * 24u;
    record->output = get_u64(cursor + 0);
    record->placement_count = get_u32(cursor + 8);
    record->focus_index = get_u32(cursor + 12);
    record->focus_generation = get_u32(cursor + 16);
    if (get_u32(cursor + 20) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_placement_record(const struct sophia_wm_v1_projection_placement_record *record, uint8_t *out, size_t capacity) {
    if (capacity < 60u) return SOPHIA_WM_V1_TRUNCATED;
    put_u32(out + 0, record->surface_index);
    put_u32(out + 4, record->surface_generation);
    put_u64(out + 8, record->state_generation);
    put_i32(out + 16, record->x);
    put_i32(out + 20, record->y);
    put_i32(out + 24, record->width);
    put_i32(out + 28, record->height);
    put_i32(out + 32, record->requested_width);
    put_i32(out + 36, record->requested_height);
    put_i32(out + 40, record->crop_x);
    put_i32(out + 44, record->crop_y);
    put_i32(out + 48, record->crop_width);
    put_i32(out + 52, record->crop_height);
    put_u16(out + 56, record->transform);
    put_u16(out + 58, record->presentation_bits);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_placement_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_projection_placement_record *record) {
    if (data_len % 60u != 0) return data_len < 60u ? SOPHIA_WM_V1_TRUNCATED : SOPHIA_WM_V1_TRAILING_BYTES;
    size_t count = data_len / 60u;
    if (count > 1024u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    if (index >= count) return SOPHIA_WM_V1_TRUNCATED;
    const uint8_t *cursor = data + index * 60u;
    record->surface_index = get_u32(cursor + 0);
    record->surface_generation = get_u32(cursor + 4);
    record->state_generation = get_u64(cursor + 8);
    record->x = get_i32(cursor + 16);
    record->y = get_i32(cursor + 20);
    record->width = get_i32(cursor + 24);
    record->height = get_i32(cursor + 28);
    record->requested_width = get_i32(cursor + 32);
    record->requested_height = get_i32(cursor + 36);
    record->crop_x = get_i32(cursor + 40);
    record->crop_y = get_i32(cursor + 44);
    record->crop_width = get_i32(cursor + 48);
    record->crop_height = get_i32(cursor + 52);
    record->transform = get_u16(cursor + 56);
    record->presentation_bits = get_u16(cursor + 58);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_indicator_record(const struct sophia_wm_v1_projection_indicator_record *record, uint8_t *out, size_t capacity) {
    if (capacity < 64u) return SOPHIA_WM_V1_TRUNCATED;
    put_u64(out + 0, record->output);
    put_u32(out + 8, record->slot);
    put_u64(out + 12, record->indicator);
    put_u64(out + 20, record->action);
    put_u16(out + 28, record->state_bits);
    put_u16(out + 30, record->label_len);
    put_bytes(out + 32, record->label, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_indicator_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_projection_indicator_record *record) {
    if (data_len % 64u != 0) return data_len < 64u ? SOPHIA_WM_V1_TRUNCATED : SOPHIA_WM_V1_TRAILING_BYTES;
    size_t count = data_len / 64u;
    if (count > 256u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    if (index >= count) return SOPHIA_WM_V1_TRUNCATED;
    const uint8_t *cursor = data + index * 64u;
    record->output = get_u64(cursor + 0);
    record->slot = get_u32(cursor + 8);
    record->indicator = get_u64(cursor + 12);
    record->action = get_u64(cursor + 20);
    record->state_bits = get_u16(cursor + 28);
    record->label_len = get_u16(cursor + 30);
    get_bytes(cursor + 32, record->label, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_output_status_record(const struct sophia_wm_v1_projection_output_status_record *record, uint8_t *out, size_t capacity) {
    if (capacity < 48u) return SOPHIA_WM_V1_TRUNCATED;
    put_u64(out + 0, record->output);
    put_u16(out + 8, record->focus_bits);
    put_u16(out + 10, record->layout_len);
    put_u32(out + 12, 0);
    put_bytes(out + 16, record->layout, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_output_status_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_projection_output_status_record *record) {
    if (data_len % 48u != 0) return data_len < 48u ? SOPHIA_WM_V1_TRUNCATED : SOPHIA_WM_V1_TRAILING_BYTES;
    size_t count = data_len / 48u;
    if (count > 16u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    if (index >= count) return SOPHIA_WM_V1_TRUNCATED;
    const uint8_t *cursor = data + index * 48u;
    record->output = get_u64(cursor + 0);
    record->focus_bits = get_u16(cursor + 8);
    record->layout_len = get_u16(cursor + 10);
    if (get_u32(cursor + 12) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    get_bytes(cursor + 16, record->layout, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_client_hello(const struct sophia_wm_v1_client_hello *message, uint8_t *out, size_t capacity, size_t *written) {
    size_t payload_len = 12u;
    enum sophia_wm_v1_status status = write_header(32u, UINT64_C(0), payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u16(cursor + 0, message->minimum_revision);
    put_u16(cursor + 2, message->maximum_revision);
    put_u64(cursor + 4, message->capabilities);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_client_hello(const uint8_t *frame, size_t frame_len, struct sophia_wm_v1_client_hello *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 32u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction != 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (payload_len < 12u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 12u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->minimum_revision = get_u16(cursor + 0);
    message->maximum_revision = get_u16(cursor + 2);
    message->capabilities = get_u64(cursor + 4);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_server_welcome(const struct sophia_wm_v1_server_welcome *message, uint8_t *out, size_t capacity, size_t *written) {
    size_t payload_len = 32u;
    enum sophia_wm_v1_status status = write_header(33u, UINT64_C(0), payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u16(cursor + 0, message->selected_revision);
    put_u16(cursor + 2, 0);
    put_u64(cursor + 4, message->capabilities);
    put_u64(cursor + 12, message->connection_epoch);
    put_u16(cursor + 20, message->max_outputs);
    put_u16(cursor + 22, message->max_bindings);
    put_u32(cursor + 24, message->max_surfaces);
    put_u32(cursor + 28, message->max_chunk_bytes);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_server_welcome(const uint8_t *frame, size_t frame_len, struct sophia_wm_v1_server_welcome *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 33u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction != 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (payload_len < 32u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 32u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->selected_revision = get_u16(cursor + 0);
    if (get_u16(cursor + 2) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    message->capabilities = get_u64(cursor + 4);
    message->connection_epoch = get_u64(cursor + 12);
    message->max_outputs = get_u16(cursor + 20);
    message->max_bindings = get_u16(cursor + 22);
    message->max_surfaces = get_u32(cursor + 24);
    message->max_chunk_bytes = get_u32(cursor + 28);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_begin(uint64_t transaction, const struct sophia_wm_v1_snapshot_begin *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 36u;
    enum sophia_wm_v1_status status = write_header(34u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->scene_generation);
    put_u64(cursor + 16, message->active_output);
    put_u16(cursor + 24, message->chunk_count);
    put_u16(cursor + 26, message->output_count);
    put_u32(cursor + 28, message->surface_count);
    put_u16(cursor + 32, message->action_count);
    put_u16(cursor + 34, message->session_operation_count);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_begin(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_snapshot_begin *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 34u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 36u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 36u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->scene_generation = get_u64(cursor + 8);
    message->active_output = get_u64(cursor + 16);
    message->chunk_count = get_u16(cursor + 24);
    message->output_count = get_u16(cursor + 26);
    message->surface_count = get_u32(cursor + 28);
    message->action_count = get_u16(cursor + 32);
    message->session_operation_count = get_u16(cursor + 34);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_chunk(uint64_t transaction, const struct sophia_wm_v1_snapshot_chunk *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (message->data_len > 65520u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    size_t payload_len = 16u + message->data_len;
    enum sophia_wm_v1_status status = write_header(35u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u16(cursor + 8, message->ordinal);
    put_u16(cursor + 10, message->record_kind);
    put_u32(cursor + 12, message->item_count);
    for (size_t index = 0; index < message->data_len; ++index) cursor[16u + index] = message->data[index];
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_chunk(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_snapshot_chunk *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 35u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 16u) return SOPHIA_WM_V1_TRUNCATED;
    size_t bytes_len = payload_len - 16u;
    if (bytes_len > 65520u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->ordinal = get_u16(cursor + 8);
    message->record_kind = get_u16(cursor + 10);
    message->item_count = get_u32(cursor + 12);
    message->data = cursor + 16;
    message->data_len = bytes_len;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_end(uint64_t transaction, const struct sophia_wm_v1_snapshot_end *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 20u;
    enum sophia_wm_v1_status status = write_header(36u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->scene_generation);
    put_u16(cursor + 16, message->chunk_count);
    put_u16(cursor + 18, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_end(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_snapshot_end *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 36u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 20u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 20u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->scene_generation = get_u64(cursor + 8);
    message->chunk_count = get_u16(cursor + 16);
    if (get_u16(cursor + 18) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_request(uint64_t transaction, const struct sophia_wm_v1_projection_request *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (message->affected_outputs_len > 128u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    size_t payload_len = 84u + message->affected_outputs_len;
    enum sophia_wm_v1_status status = write_header(37u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->request_id);
    put_u64(cursor + 16, message->scene_generation);
    put_u64(cursor + 24, message->policy_generation);
    put_u16(cursor + 32, message->cause_kind);
    put_u16(cursor + 34, message->interaction_phase);
    put_u16(cursor + 36, message->interaction_kind);
    put_u16(cursor + 38, message->interaction_axis);
    put_u64(cursor + 40, message->activation_serial);
    put_u64(cursor + 48, message->action);
    put_u32(cursor + 56, message->target_index);
    put_u32(cursor + 60, message->target_generation);
    put_i32(cursor + 64, message->interaction_x);
    put_i32(cursor + 68, message->interaction_y);
    put_i32(cursor + 72, message->interaction_width);
    put_i32(cursor + 76, message->interaction_height);
    put_u16(cursor + 80, message->affected_output_count);
    put_u16(cursor + 82, 0);
    for (size_t index = 0; index < message->affected_outputs_len; ++index) cursor[84u + index] = message->affected_outputs[index];
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_request(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_request *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 37u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 84u) return SOPHIA_WM_V1_TRUNCATED;
    size_t bytes_len = payload_len - 84u;
    if (bytes_len > 128u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->request_id = get_u64(cursor + 8);
    message->scene_generation = get_u64(cursor + 16);
    message->policy_generation = get_u64(cursor + 24);
    message->cause_kind = get_u16(cursor + 32);
    message->interaction_phase = get_u16(cursor + 34);
    message->interaction_kind = get_u16(cursor + 36);
    message->interaction_axis = get_u16(cursor + 38);
    message->activation_serial = get_u64(cursor + 40);
    message->action = get_u64(cursor + 48);
    message->target_index = get_u32(cursor + 56);
    message->target_generation = get_u32(cursor + 60);
    message->interaction_x = get_i32(cursor + 64);
    message->interaction_y = get_i32(cursor + 68);
    message->interaction_width = get_i32(cursor + 72);
    message->interaction_height = get_i32(cursor + 76);
    message->affected_output_count = get_u16(cursor + 80);
    if (get_u16(cursor + 82) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    message->affected_outputs = cursor + 84;
    message->affected_outputs_len = bytes_len;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_begin(uint64_t transaction, const struct sophia_wm_v1_projection_begin *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 44u;
    enum sophia_wm_v1_status status = write_header(38u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->request_id);
    put_u64(cursor + 16, message->base_generation);
    put_u64(cursor + 24, message->active_output);
    put_u16(cursor + 32, message->chunk_count);
    put_u16(cursor + 34, message->output_count);
    put_u32(cursor + 36, message->placement_count);
    put_u16(cursor + 40, message->indicator_count);
    put_u16(cursor + 42, message->status_count);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_begin(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_begin *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 38u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 44u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 44u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->request_id = get_u64(cursor + 8);
    message->base_generation = get_u64(cursor + 16);
    message->active_output = get_u64(cursor + 24);
    message->chunk_count = get_u16(cursor + 32);
    message->output_count = get_u16(cursor + 34);
    message->placement_count = get_u32(cursor + 36);
    message->indicator_count = get_u16(cursor + 40);
    message->status_count = get_u16(cursor + 42);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_chunk(uint64_t transaction, const struct sophia_wm_v1_projection_chunk *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (message->data_len > 65520u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    size_t payload_len = 16u + message->data_len;
    enum sophia_wm_v1_status status = write_header(39u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u16(cursor + 8, message->ordinal);
    put_u16(cursor + 10, message->record_kind);
    put_u32(cursor + 12, message->item_count);
    for (size_t index = 0; index < message->data_len; ++index) cursor[16u + index] = message->data[index];
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_chunk(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_chunk *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 39u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 16u) return SOPHIA_WM_V1_TRUNCATED;
    size_t bytes_len = payload_len - 16u;
    if (bytes_len > 65520u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->ordinal = get_u16(cursor + 8);
    message->record_kind = get_u16(cursor + 10);
    message->item_count = get_u32(cursor + 12);
    message->data = cursor + 16;
    message->data_len = bytes_len;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_end(uint64_t transaction, const struct sophia_wm_v1_projection_end *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 28u;
    enum sophia_wm_v1_status status = write_header(40u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->request_id);
    put_u64(cursor + 16, message->base_generation);
    put_u16(cursor + 24, message->chunk_count);
    put_u16(cursor + 26, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_end(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_end *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 40u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 28u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 28u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->request_id = get_u64(cursor + 8);
    message->base_generation = get_u64(cursor + 16);
    message->chunk_count = get_u16(cursor + 24);
    if (get_u16(cursor + 26) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_projection_outcome(uint64_t transaction, const struct sophia_wm_v1_projection_outcome *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 28u;
    enum sophia_wm_v1_status status = write_header(41u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->request_id);
    put_u64(cursor + 16, message->scene_generation);
    put_u16(cursor + 24, message->outcome);
    put_u16(cursor + 26, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_projection_outcome(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_outcome *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 41u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 28u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 28u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->request_id = get_u64(cursor + 8);
    message->scene_generation = get_u64(cursor + 16);
    message->outcome = get_u16(cursor + 24);
    if (get_u16(cursor + 26) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_policy_configuration(uint64_t transaction, const struct sophia_wm_v1_policy_configuration *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (message->actions_len > 35840u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    size_t payload_len = 40u + message->actions_len;
    enum sophia_wm_v1_status status = write_header(42u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->configuration_generation);
    put_u16(cursor + 16, message->action_count);
    put_u16(cursor + 18, message->style_bits);
    put_u32(cursor + 20, message->focus_ring_width);
    put_u32(cursor + 24, message->focus_ring_color);
    put_u32(cursor + 28, message->frame_width);
    put_u32(cursor + 32, message->frame_focused_color);
    put_u32(cursor + 36, message->frame_unfocused_color);
    for (size_t index = 0; index < message->actions_len; ++index) cursor[40u + index] = message->actions[index];
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_policy_configuration(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_policy_configuration *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 42u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 40u) return SOPHIA_WM_V1_TRUNCATED;
    size_t bytes_len = payload_len - 40u;
    if (bytes_len > 35840u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->configuration_generation = get_u64(cursor + 8);
    message->action_count = get_u16(cursor + 16);
    message->style_bits = get_u16(cursor + 18);
    message->focus_ring_width = get_u32(cursor + 20);
    message->focus_ring_color = get_u32(cursor + 24);
    message->frame_width = get_u32(cursor + 28);
    message->frame_focused_color = get_u32(cursor + 32);
    message->frame_unfocused_color = get_u32(cursor + 36);
    message->actions = cursor + 40;
    message->actions_len = bytes_len;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_policy_configuration_outcome(uint64_t transaction, const struct sophia_wm_v1_policy_configuration_outcome *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 20u;
    enum sophia_wm_v1_status status = write_header(43u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->configuration_generation);
    put_u16(cursor + 16, message->outcome);
    put_u16(cursor + 18, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_policy_configuration_outcome(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_policy_configuration_outcome *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 43u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 20u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 20u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->configuration_generation = get_u64(cursor + 8);
    message->outcome = get_u16(cursor + 16);
    if (get_u16(cursor + 18) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_policy_dirty(uint64_t transaction, const struct sophia_wm_v1_policy_dirty *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (message->affected_outputs_len > 128u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    size_t payload_len = 20u + message->affected_outputs_len;
    enum sophia_wm_v1_status status = write_header(44u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->policy_generation);
    put_u16(cursor + 16, message->affected_output_count);
    put_u16(cursor + 18, 0);
    for (size_t index = 0; index < message->affected_outputs_len; ++index) cursor[20u + index] = message->affected_outputs[index];
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_policy_dirty(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_policy_dirty *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 44u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 20u) return SOPHIA_WM_V1_TRUNCATED;
    size_t bytes_len = payload_len - 20u;
    if (bytes_len > 128u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->policy_generation = get_u64(cursor + 8);
    message->affected_output_count = get_u16(cursor + 16);
    if (get_u16(cursor + 18) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    message->affected_outputs = cursor + 20;
    message->affected_outputs_len = bytes_len;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_session_operation_request(uint64_t transaction, const struct sophia_wm_v1_session_operation_request *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 32u;
    enum sophia_wm_v1_status status = write_header(45u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->request_id);
    put_u64(cursor + 16, message->operation);
    put_u32(cursor + 24, message->target_index);
    put_u32(cursor + 28, message->target_generation);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_session_operation_request(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_session_operation_request *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 45u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 32u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 32u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->request_id = get_u64(cursor + 8);
    message->operation = get_u64(cursor + 16);
    message->target_index = get_u32(cursor + 24);
    message->target_generation = get_u32(cursor + 28);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_session_operation_outcome(uint64_t transaction, const struct sophia_wm_v1_session_operation_outcome *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 20u;
    enum sophia_wm_v1_status status = write_header(46u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->request_id);
    put_u16(cursor + 16, message->outcome);
    put_u16(cursor + 18, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_session_operation_outcome(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_session_operation_outcome *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 46u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 20u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 20u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->request_id = get_u64(cursor + 8);
    message->outcome = get_u16(cursor + 16);
    if (get_u16(cursor + 18) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_profile_prepare(uint64_t transaction, const struct sophia_wm_v1_profile_prepare *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 48u;
    enum sophia_wm_v1_status status = write_header(47u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->profile_generation);
    put_bytes(cursor + 16, message->profile_digest, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_profile_prepare(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_prepare *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 47u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 48u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 48u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->profile_generation = get_u64(cursor + 8);
    get_bytes(cursor + 16, message->profile_digest, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_profile_prepared(uint64_t transaction, const struct sophia_wm_v1_profile_prepared *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 52u;
    enum sophia_wm_v1_status status = write_header(48u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->profile_generation);
    put_bytes(cursor + 16, message->profile_digest, 32u);
    put_u16(cursor + 48, message->outcome);
    put_u16(cursor + 50, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_profile_prepared(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_prepared *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 48u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 52u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 52u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->profile_generation = get_u64(cursor + 8);
    get_bytes(cursor + 16, message->profile_digest, 32u);
    message->outcome = get_u16(cursor + 48);
    if (get_u16(cursor + 50) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_profile_activate(uint64_t transaction, const struct sophia_wm_v1_profile_activate *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 48u;
    enum sophia_wm_v1_status status = write_header(49u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->profile_generation);
    put_bytes(cursor + 16, message->profile_digest, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_profile_activate(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_activate *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 49u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 48u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 48u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->profile_generation = get_u64(cursor + 8);
    get_bytes(cursor + 16, message->profile_digest, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_profile_active(uint64_t transaction, const struct sophia_wm_v1_profile_active *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 52u;
    enum sophia_wm_v1_status status = write_header(50u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->profile_generation);
    put_bytes(cursor + 16, message->profile_digest, 32u);
    put_u16(cursor + 48, message->outcome);
    put_u16(cursor + 50, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_profile_active(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_active *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 50u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 52u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 52u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->profile_generation = get_u64(cursor + 8);
    get_bytes(cursor + 16, message->profile_digest, 32u);
    message->outcome = get_u16(cursor + 48);
    if (get_u16(cursor + 50) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_profile_rollback(uint64_t transaction, const struct sophia_wm_v1_profile_rollback *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 48u;
    enum sophia_wm_v1_status status = write_header(51u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->profile_generation);
    put_bytes(cursor + 16, message->profile_digest, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_profile_rollback(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_rollback *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 51u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 48u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 48u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->profile_generation = get_u64(cursor + 8);
    get_bytes(cursor + 16, message->profile_digest, 32u);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_profile_rolled_back(uint64_t transaction, const struct sophia_wm_v1_profile_rolled_back *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 52u;
    enum sophia_wm_v1_status status = write_header(52u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->profile_generation);
    put_bytes(cursor + 16, message->profile_digest, 32u);
    put_u16(cursor + 48, message->outcome);
    put_u16(cursor + 50, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_profile_rolled_back(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_rolled_back *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 52u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 52u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 52u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->profile_generation = get_u64(cursor + 8);
    get_bytes(cursor + 16, message->profile_digest, 32u);
    message->outcome = get_u16(cursor + 48);
    if (get_u16(cursor + 50) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_output_action_request(uint64_t transaction, const struct sophia_wm_v1_output_action_request *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (message->affected_outputs_len > 128u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    size_t payload_len = 68u + message->affected_outputs_len;
    enum sophia_wm_v1_status status = write_header(53u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->request_id);
    put_u64(cursor + 16, message->scene_generation);
    put_u64(cursor + 24, message->policy_generation);
    put_u64(cursor + 32, message->activation_serial);
    put_u64(cursor + 40, message->action);
    put_u64(cursor + 48, message->output);
    put_u64(cursor + 56, message->output_generation);
    put_u16(cursor + 64, message->affected_output_count);
    put_u16(cursor + 66, 0);
    for (size_t index = 0; index < message->affected_outputs_len; ++index) cursor[68u + index] = message->affected_outputs[index];
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_output_action_request(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_output_action_request *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 53u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 68u) return SOPHIA_WM_V1_TRUNCATED;
    size_t bytes_len = payload_len - 68u;
    if (bytes_len > 128u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->request_id = get_u64(cursor + 8);
    message->scene_generation = get_u64(cursor + 16);
    message->policy_generation = get_u64(cursor + 24);
    message->activation_serial = get_u64(cursor + 32);
    message->action = get_u64(cursor + 40);
    message->output = get_u64(cursor + 48);
    message->output_generation = get_u64(cursor + 56);
    message->affected_output_count = get_u16(cursor + 64);
    if (get_u16(cursor + 66) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    message->affected_outputs = cursor + 68;
    message->affected_outputs_len = bytes_len;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_presentation_action_request(uint64_t transaction, const struct sophia_wm_v1_presentation_action_request *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    if (message->affected_outputs_len > 128u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    size_t payload_len = 100u + message->affected_outputs_len;
    enum sophia_wm_v1_status status = write_header(54u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->request_id);
    put_u64(cursor + 16, message->scene_generation);
    put_u64(cursor + 24, message->policy_generation);
    put_u64(cursor + 32, message->activation_serial);
    put_u64(cursor + 40, message->action);
    put_u64(cursor + 48, message->output);
    put_u64(cursor + 56, message->output_generation);
    put_u64(cursor + 64, message->publication_generation);
    put_u64(cursor + 72, message->presentation_epoch);
    put_u64(cursor + 80, message->target_id);
    put_u64(cursor + 88, message->target_generation);
    put_u16(cursor + 96, message->affected_output_count);
    put_u16(cursor + 98, 0);
    for (size_t index = 0; index < message->affected_outputs_len; ++index) cursor[100u + index] = message->affected_outputs[index];
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_presentation_action_request(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_presentation_action_request *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 54u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 100u) return SOPHIA_WM_V1_TRUNCATED;
    size_t bytes_len = payload_len - 100u;
    if (bytes_len > 128u) return SOPHIA_WM_V1_FIELD_TOO_LARGE;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->request_id = get_u64(cursor + 8);
    message->scene_generation = get_u64(cursor + 16);
    message->policy_generation = get_u64(cursor + 24);
    message->activation_serial = get_u64(cursor + 32);
    message->action = get_u64(cursor + 40);
    message->output = get_u64(cursor + 48);
    message->output_generation = get_u64(cursor + 56);
    message->publication_generation = get_u64(cursor + 64);
    message->presentation_epoch = get_u64(cursor + 72);
    message->target_id = get_u64(cursor + 80);
    message->target_generation = get_u64(cursor + 88);
    message->affected_output_count = get_u16(cursor + 96);
    if (get_u16(cursor + 98) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    message->affected_outputs = cursor + 100;
    message->affected_outputs_len = bytes_len;
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_encode_presentation_outcome(uint64_t transaction, const struct sophia_wm_v1_presentation_outcome *message, uint8_t *out, size_t capacity, size_t *written) {
    if (transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    size_t payload_len = 44u;
    enum sophia_wm_v1_status status = write_header(55u, transaction, payload_len, out, capacity, written);
    if (status != SOPHIA_WM_V1_OK) return status;
    uint8_t *cursor = out + SOPHIA_IPC_HEADER_LEN;
    put_u64(cursor + 0, message->connection_epoch);
    put_u64(cursor + 8, message->publication_generation);
    put_u64(cursor + 16, message->output);
    put_u64(cursor + 24, message->output_generation);
    put_u64(cursor + 32, message->presentation_epoch);
    put_u16(cursor + 40, message->outcome);
    put_u16(cursor + 42, 0);
    return SOPHIA_WM_V1_OK;
}

enum sophia_wm_v1_status sophia_wm_v1_decode_presentation_outcome(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_presentation_outcome *message) {
    uint64_t frame_transaction = 0;
    size_t payload_len = 0;
    enum sophia_wm_v1_status status = read_header(frame, frame_len, 55u, &frame_transaction, &payload_len);
    if (status != SOPHIA_WM_V1_OK) return status;
    if (frame_transaction == 0) return SOPHIA_WM_V1_INVALID_TRANSACTION;
    *transaction = frame_transaction;
    if (payload_len < 44u) return SOPHIA_WM_V1_TRUNCATED;
    if (payload_len > 44u) return SOPHIA_WM_V1_TRAILING_BYTES;
    const uint8_t *cursor = frame + SOPHIA_IPC_HEADER_LEN;
    message->connection_epoch = get_u64(cursor + 0);
    message->publication_generation = get_u64(cursor + 8);
    message->output = get_u64(cursor + 16);
    message->output_generation = get_u64(cursor + 24);
    message->presentation_epoch = get_u64(cursor + 32);
    message->outcome = get_u16(cursor + 40);
    if (get_u16(cursor + 42) != 0) return SOPHIA_WM_V1_RESERVED_NONZERO;
    return SOPHIA_WM_V1_OK;
}
