/* Field tables transcribed from sophia-shell-files-v1.kdl at bae4ec4a9. */
#ifndef SOPHIA_SHELL_FILES_CONTENT_H
#define SOPHIA_SHELL_FILES_CONTENT_H
#include <stdint.h>
struct sophia_sf_content_output_facts_entry {
    uint64_t output_id;
    uint64_t output_generation;
    uint32_t local_width;
    uint32_t local_height;
    uint32_t scale_numerator;
    uint32_t scale_denominator;
    uint64_t scale_generation;
};
struct sophia_sf_content_surface {
    uint64_t allocation_id;
    uint64_t allocation_generation;
    uint64_t scale_generation;
    uint16_t role;
    uint16_t edge;
    int16_t margin_top;
    int16_t margin_right;
    int16_t margin_bottom;
    int16_t margin_left;
    uint32_t reservation_extent;
    uint16_t parent_surface_index;
    int32_t anchor_x;
    int32_t anchor_y;
    uint32_t anchor_width;
    uint32_t anchor_height;
};
struct sophia_sf_content_placement {
    uint64_t resource_id;
    uint64_t resource_generation;
    uint16_t surface_index;
    int32_t destination_x_px;
    int32_t destination_y_px;
};
struct sophia_sf_content_target {
    uint16_t surface_index;
    uint16_t action_kind;
    uint64_t target_id;
    uint64_t target_generation;
    uint64_t action_id;
    int32_t bounds_x;
    int32_t bounds_y;
    uint32_t bounds_width;
    uint32_t bounds_height;
};
struct sophia_sf_limits {
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t limits_generation;
    uint64_t max_resource_bytes;
    uint64_t max_staging_bytes;
    uint64_t max_resident_bytes;
    uint64_t max_retiring_bytes;
    uint64_t max_session_retiring_bytes;
    uint64_t pixel_format_mask;
    uint64_t effect_mask;
    uint32_t max_frame_payload;
    uint32_t max_chunk_bytes;
    uint32_t max_width_px;
    uint32_t max_height_px;
    uint32_t max_live_resources;
    uint32_t max_resource_ids;
    uint32_t max_open_transfers;
    uint32_t max_outputs;
    uint32_t max_allocations_total;
    uint32_t max_allocations_per_output;
    uint32_t max_panels_per_output;
    uint32_t max_popouts_per_output;
    uint32_t max_candidate_surfaces;
    uint32_t max_candidate_placements;
    uint32_t max_candidate_targets;
    uint32_t max_candidate_bytes;
    uint32_t max_pending_allocation_requests;
    uint32_t max_open_candidates_total;
    uint32_t max_open_candidates_per_output;
    uint32_t max_pending_candidates_total;
    uint32_t max_pending_candidates_per_output;
    uint32_t max_pending_actions;
    uint32_t max_frame_demands_per_output;
    uint32_t max_control_records;
    uint32_t reserved_control_queue_bytes;
    uint32_t max_input_queue_bytes;
    uint32_t max_output_queue_bytes;
    uint32_t max_frames_per_service_tick;
    uint32_t max_panel_extent;
    uint32_t max_popout_extent_px;
    uint32_t max_reservation_extent;
    uint32_t max_content_coverage_percent;
    uint32_t max_margin_logical;
    uint32_t max_scale_numerator;
    uint32_t max_scale_denominator;
    uint32_t allocation_timeout_ms;
    uint32_t transfer_timeout_ms;
    uint32_t transfer_idle_timeout_ms;
    uint32_t candidate_timeout_ms;
    uint32_t preparation_timeout_ms;
    uint32_t presentation_timeout_ms;
    uint32_t action_ack_timeout_ms;
    uint32_t permit_timeout_ms;
    uint32_t peer_write_timeout_ms;
    uint32_t max_candidate_rate_millihz;
};
struct sophia_sf_outputs {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t facts_generation;
    uint32_t output_count;
    struct sophia_sf_content_output_facts_entry outputs[16];
};
struct sophia_sf_negotiate {
    uint16_t minimum_revision;
    uint16_t maximum_revision;
    uint64_t required_capabilities;
};
struct sophia_sf_negotiated {
    uint16_t selected_revision;
    uint64_t connection_epoch;
    uint64_t capabilities;
    uint16_t max_descriptors;
    uint16_t max_label_bytes;
    uint16_t max_pending_activations;
    uint16_t limits_published;
};
struct sophia_sf_refused {
    uint16_t reason;
    uint64_t denied_capabilities;
};
struct sophia_sf_submitted {
    uint64_t submission_id;
    uint16_t candidate_kind;
};
struct sophia_sf_object_published {
    uint16_t object_kind;
    uint64_t generation;
    uint64_t qid;
};
struct sophia_sf_allocation_request {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t output_id;
    uint64_t output_generation;
    uint64_t allocation_request_id;
    uint16_t operation;
    uint16_t role;
    uint16_t edge;
    uint64_t prior_id;
    uint64_t prior_generation;
    uint64_t parent_id;
    uint64_t parent_generation;
    uint64_t parent_presentation_epoch;
    int32_t anchor_x;
    int32_t anchor_y;
    uint32_t anchor_width;
    uint32_t anchor_height;
    uint32_t desired_width;
    uint32_t desired_height;
    int16_t margin_top;
    int16_t margin_right;
    int16_t margin_bottom;
    int16_t margin_left;
};
struct sophia_sf_allocation_result {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t allocation_request_id;
    uint16_t status;
    uint16_t reason;
    uint64_t output_id;
    uint64_t output_generation;
    uint64_t allocation_id;
    uint64_t allocation_generation;
    uint64_t parent_id;
    uint64_t parent_generation;
    uint64_t scale_generation;
    int32_t logical_x;
    int32_t logical_y;
    uint32_t logical_width;
    uint32_t logical_height;
    int32_t pixel_x;
    int32_t pixel_y;
    uint32_t pixel_width;
    uint32_t pixel_height;
    uint32_t scale_numerator;
    uint32_t scale_denominator;
    uint32_t allowed_reservation_extent;
    int16_t margin_top;
    int16_t margin_right;
    int16_t margin_bottom;
    int16_t margin_left;
    int32_t acknowledged_anchor_x;
    int32_t acknowledged_anchor_y;
    uint32_t acknowledged_anchor_width;
    uint32_t acknowledged_anchor_height;
};
struct sophia_sf_resource_begin {
    uint64_t transaction;
    uint16_t slot;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t resource_id;
    uint64_t resource_generation;
    uint32_t width_px;
    uint32_t height_px;
    uint32_t rendered_scale_numerator;
    uint32_t rendered_scale_denominator;
    uint16_t pixel_format;
    uint32_t chunk_count;
    uint64_t total_bytes;
};
struct sophia_sf_resource_end {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t resource_id;
    uint64_t resource_generation;
    uint64_t total_bytes;
    uint32_t chunk_count;
};
struct sophia_sf_resource_cancel {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t resource_id;
    uint64_t resource_generation;
};
struct sophia_sf_resource_retire {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t resource_id;
    uint64_t resource_generation;
};
struct sophia_sf_resource_status {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t resource_id;
    uint64_t resource_generation;
    uint16_t status;
    uint16_t reason;
    uint32_t next_ordinal;
    uint64_t admitted_bytes;
};
struct sophia_sf_resource_released {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t resource_id;
    uint64_t resource_generation;
    uint16_t reason;
};
struct sophia_sf_candidate {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t candidate_generation;
    uint64_t output_id;
    uint64_t output_generation;
    uint64_t facts_generation;
    uint64_t pacing_permit;
    uint64_t interaction_generation;
    uint16_t surface_count;
    uint16_t placement_count;
    uint16_t target_count;
    struct sophia_sf_content_surface surfaces[8];
    struct sophia_sf_content_placement placements[32];
    struct sophia_sf_content_target targets[64];
};
struct sophia_sf_frame_demand {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t output_id;
    uint64_t output_generation;
    uint64_t allocation_id;
    uint64_t allocation_generation;
    uint64_t demand_id;
    uint16_t reason;
};
struct sophia_sf_frame_demand_cancel {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t output_id;
    uint64_t output_generation;
    uint64_t demand_id;
    uint64_t permit_id;
};
struct sophia_sf_frame_permit {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t output_id;
    uint64_t output_generation;
    uint64_t demand_id;
    uint64_t permit_id;
    uint16_t state;
    uint16_t reason;
    uint32_t ttl_ms;
    uint32_t max_candidate_bytes;
};
struct sophia_sf_action {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t output_id;
    uint64_t output_generation;
    uint64_t candidate_generation;
    uint64_t presentation_epoch;
    uint64_t interaction_generation;
    uint64_t allocation_id;
    uint64_t allocation_generation;
    uint64_t target_id;
    uint64_t target_generation;
    uint64_t action_id;
    uint64_t event_id;
    uint16_t kind;
    uint16_t reason;
};
struct sophia_sf_action_ack {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t output_id;
    uint64_t output_generation;
    uint64_t candidate_generation;
    uint64_t presentation_epoch;
    uint64_t interaction_generation;
    uint64_t allocation_id;
    uint64_t allocation_generation;
    uint64_t target_id;
    uint64_t target_generation;
    uint64_t action_id;
    uint64_t event_id;
    uint16_t disposition;
};
struct sophia_sf_candidate_outcome {
    uint64_t transaction;
    uint64_t grant_connection_epoch;
    uint64_t grant_content_epoch;
    uint64_t candidate_generation;
    uint64_t output_id;
    uint64_t output_generation;
    uint16_t kind;
    uint16_t reason;
    uint64_t presentation_epoch;
    uint64_t work_area_generation;
    uint64_t wm_commit_generation;
};
#endif
