/* Generated by tools/generate_wm_rows.py from spec/sophia-wm-files-v1.kdl row-layouts. */
#ifndef SOPHIA_WM_RECORDS_H
#define SOPHIA_WM_RECORDS_H
#include <stddef.h>
#include <stdint.h>
#define SOPHIA_WF_CAP_BINDINGS (UINT64_C(1) << 0)
#define SOPHIA_WF_CAP_ACTIONS (UINT64_C(1) << 1)
#define SOPHIA_WF_CAP_MULTI_OUTPUT (UINT64_C(1) << 2)
#define SOPHIA_WF_CAP_POINTER_INTERACTIONS (UINT64_C(1) << 3)
#define SOPHIA_WF_CAP_CHROME (UINT64_C(1) << 4)
#define SOPHIA_WF_CAP_POLICY_DIRTY (UINT64_C(1) << 5)
#define SOPHIA_WF_CAP_CONFIGURATION (UINT64_C(1) << 6)
#define SOPHIA_WF_CAP_SESSION_OPERATIONS (UINT64_C(1) << 7)
#define SOPHIA_WF_CAP_INDICATORS (UINT64_C(1) << 8)
#define SOPHIA_WF_CAP_PROFILE_ACTIVATION (UINT64_C(1) << 9)
#define SOPHIA_WF_CAP_LAUNCH_PLACEMENT (UINT64_C(1) << 10)
#define SOPHIA_WF_CAP_TAB_GROUPS (UINT64_C(1) << 11)
#define SOPHIA_WF_CAP_TRANSLATION_GROUPS (UINT64_C(1) << 12)
#define SOPHIA_WF_CAP_POINTER_FOCUS (UINT64_C(1) << 13)
#define SOPHIA_WF_CAP_LAUNCH_ORIGIN (UINT64_C(1) << 14)
#define SOPHIA_WF_CAP_OUTPUT_ACTIONS (UINT64_C(1) << 15)
#define SOPHIA_WF_CAP_OUTPUT_POLICY_KEYS (UINT64_C(1) << 16)
#define SOPHIA_WF_CAP_OUTPUT_LAUNCH_CONTEXT (UINT64_C(1) << 17)
#define SOPHIA_WF_CAP_SURFACE_INSTANCES (UINT64_C(1) << 18)
#define SOPHIA_WF_CAP_PRESENTATION_ACTIONS (UINT64_C(1) << 19)
#define SOPHIA_WF_CAP_ACTION_LIFECYCLE (UINT64_C(1) << 20)
/* Fixed rows only; no socket headers or transfer framing.
 * Decode and encode check width and reserved bytes. Complete file-record
 * validation additionally checks sections and negotiated capabilities.
 * Outputs are unchanged on error. Return 0, -1 invalid, -4 argument/space.
 * Destination must not overlap the value or its source bytes. */
#define SOPHIA_WF_SNAPSHOT_OUTPUT_BYTES 56u
struct sophia_wf_snapshot_output {
    uint64_t output;
    uint64_t generation;
    uint32_t focus_index;
    uint32_t focus_generation;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t work_x;
    int32_t work_y;
    int32_t work_width;
    int32_t work_height;
};
int sophia_wf_snapshot_output_decode(const void *, size_t, struct sophia_wf_snapshot_output *);
int sophia_wf_snapshot_output_encode(void *, size_t, const struct sophia_wf_snapshot_output *);
#define SOPHIA_WF_SNAPSHOT_SURFACE_BYTES 80u
struct sophia_wf_snapshot_surface {
    uint32_t surface_index;
    uint32_t surface_generation;
    uint64_t state_generation;
    uint64_t current_output;
    uint16_t capability_bits;
    uint16_t kind;
    uint16_t request_state_bits;
    uint16_t current_state_bits;
    uint32_t transient_index;
    uint32_t transient_generation;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t min_width;
    int32_t min_height;
    int32_t max_width;
    int32_t max_height;
    int32_t exact_width;
    int32_t exact_height;
};
int sophia_wf_snapshot_surface_decode(const void *, size_t, struct sophia_wf_snapshot_surface *);
int sophia_wf_snapshot_surface_encode(void *, size_t, const struct sophia_wf_snapshot_surface *);
#define SOPHIA_WF_SNAPSHOT_ACTION_BYTES 140u
struct sophia_wf_snapshot_action {
    uint64_t action;
    uint16_t session_operation_slot;
    uint16_t name_len;
    uint8_t name[128];
};
int sophia_wf_snapshot_action_decode(const void *, size_t, struct sophia_wf_snapshot_action *);
int sophia_wf_snapshot_action_encode(void *, size_t, const struct sophia_wf_snapshot_action *);
#define SOPHIA_WF_SNAPSHOT_SESSION_OPERATION_BYTES 12u
struct sophia_wf_snapshot_session_operation {
    uint64_t operation;
    uint16_t slot;
    uint16_t target_bits;
};
int sophia_wf_snapshot_session_operation_decode(const void *, size_t, struct sophia_wf_snapshot_session_operation *);
int sophia_wf_snapshot_session_operation_encode(void *, size_t, const struct sophia_wf_snapshot_session_operation *);
#define SOPHIA_WF_PROJECTION_OUTPUT_BYTES 24u
struct sophia_wf_projection_output {
    uint64_t output;
    uint32_t placement_count;
    uint32_t focus_index;
    uint32_t focus_generation;
};
int sophia_wf_projection_output_decode(const void *, size_t, struct sophia_wf_projection_output *);
int sophia_wf_projection_output_encode(void *, size_t, const struct sophia_wf_projection_output *);
#define SOPHIA_WF_PROJECTION_PLACEMENT_BYTES 60u
struct sophia_wf_projection_placement {
    uint32_t surface_index;
    uint32_t surface_generation;
    uint64_t state_generation;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t requested_width;
    int32_t requested_height;
    int32_t crop_x;
    int32_t crop_y;
    int32_t crop_width;
    int32_t crop_height;
    uint16_t transform;
    uint16_t presentation_bits;
};
int sophia_wf_projection_placement_decode(const void *, size_t, struct sophia_wf_projection_placement *);
int sophia_wf_projection_placement_encode(void *, size_t, const struct sophia_wf_projection_placement *);
#define SOPHIA_WF_PROJECTION_INDICATOR_BYTES 64u
struct sophia_wf_projection_indicator {
    uint64_t output;
    uint32_t slot;
    uint64_t indicator;
    uint64_t action;
    uint16_t state_bits;
    uint16_t label_len;
    uint8_t label[32];
};
int sophia_wf_projection_indicator_decode(const void *, size_t, struct sophia_wf_projection_indicator *);
int sophia_wf_projection_indicator_encode(void *, size_t, const struct sophia_wf_projection_indicator *);
#define SOPHIA_WF_PROJECTION_OUTPUT_STATUS_BYTES 48u
struct sophia_wf_projection_output_status {
    uint64_t output;
    uint16_t focus_bits;
    uint16_t layout_len;
    uint8_t layout[32];
};
int sophia_wf_projection_output_status_decode(const void *, size_t, struct sophia_wf_projection_output_status *);
int sophia_wf_projection_output_status_encode(void *, size_t, const struct sophia_wf_projection_output_status *);
#define SOPHIA_WF_SNAPSHOT_SURFACE_CLASSIFICATION_BYTES 16u
struct sophia_wf_snapshot_surface_classification {
    uint32_t surface_index;
    uint32_t surface_generation;
    uint64_t classification;
};
int sophia_wf_snapshot_surface_classification_decode(const void *, size_t, struct sophia_wf_snapshot_surface_classification *);
int sophia_wf_snapshot_surface_classification_encode(void *, size_t, const struct sophia_wf_snapshot_surface_classification *);
#define SOPHIA_WF_PROJECTION_LAUNCH_CONTEXT_BYTES 24u
struct sophia_wf_projection_launch_context {
    uint32_t surface_index;
    uint32_t surface_generation;
    uint64_t epoch;
    uint64_t token;
};
int sophia_wf_projection_launch_context_decode(const void *, size_t, struct sophia_wf_projection_launch_context *);
int sophia_wf_projection_launch_context_encode(void *, size_t, const struct sophia_wf_projection_launch_context *);
#define SOPHIA_WF_PROJECTION_OUTPUT_LAUNCH_CONTEXT_BYTES 32u
struct sophia_wf_projection_output_launch_context {
    uint64_t output;
    uint64_t generation;
    uint64_t epoch;
    uint64_t token;
};
int sophia_wf_projection_output_launch_context_decode(const void *, size_t, struct sophia_wf_projection_output_launch_context *);
int sophia_wf_projection_output_launch_context_encode(void *, size_t, const struct sophia_wf_projection_output_launch_context *);
#define SOPHIA_WF_SNAPSHOT_LAUNCH_ORIGIN_BYTES 24u
struct sophia_wf_snapshot_launch_origin {
    uint32_t surface_index;
    uint32_t surface_generation;
    uint64_t epoch;
    uint64_t token;
};
int sophia_wf_snapshot_launch_origin_decode(const void *, size_t, struct sophia_wf_snapshot_launch_origin *);
int sophia_wf_snapshot_launch_origin_encode(void *, size_t, const struct sophia_wf_snapshot_launch_origin *);
#define SOPHIA_WF_SNAPSHOT_OUTPUT_POLICY_KEY_BYTES 24u
struct sophia_wf_snapshot_output_policy_key {
    uint64_t output;
    uint64_t generation;
    uint64_t policy_key;
};
int sophia_wf_snapshot_output_policy_key_decode(const void *, size_t, struct sophia_wf_snapshot_output_policy_key *);
int sophia_wf_snapshot_output_policy_key_encode(void *, size_t, const struct sophia_wf_snapshot_output_policy_key *);
#define SOPHIA_WF_PROJECTION_TAB_GROUP_BYTES 48u
struct sophia_wf_projection_tab_group {
    uint64_t output;
    uint64_t group;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    uint32_t selected_index;
    uint32_t selected_generation;
    uint32_t member_count;
    uint32_t focused;
};
int sophia_wf_projection_tab_group_decode(const void *, size_t, struct sophia_wf_projection_tab_group *);
int sophia_wf_projection_tab_group_encode(void *, size_t, const struct sophia_wf_projection_tab_group *);
#define SOPHIA_WF_PROJECTION_TAB_MEMBER_BYTES 24u
struct sophia_wf_projection_tab_member {
    uint64_t output;
    uint64_t group;
    uint32_t surface_index;
    uint32_t surface_generation;
};
int sophia_wf_projection_tab_member_decode(const void *, size_t, struct sophia_wf_projection_tab_member *);
int sophia_wf_projection_tab_member_encode(void *, size_t, const struct sophia_wf_projection_tab_member *);
#define SOPHIA_WF_PROJECTION_TRANSLATION_GROUP_BYTES 32u
struct sophia_wf_projection_translation_group {
    uint64_t output;
    uint64_t group;
    int32_t x;
    int32_t y;
    uint32_t member_count;
};
int sophia_wf_projection_translation_group_decode(const void *, size_t, struct sophia_wf_projection_translation_group *);
int sophia_wf_projection_translation_group_encode(void *, size_t, const struct sophia_wf_projection_translation_group *);
#define SOPHIA_WF_PROJECTION_TRANSLATION_MEMBER_BYTES 24u
struct sophia_wf_projection_translation_member {
    uint64_t output;
    uint64_t group;
    uint32_t surface_index;
    uint32_t surface_generation;
};
int sophia_wf_projection_translation_member_decode(const void *, size_t, struct sophia_wf_projection_translation_member *);
int sophia_wf_projection_translation_member_encode(void *, size_t, const struct sophia_wf_projection_translation_member *);
#define SOPHIA_WF_PROJECTION_PRESENTATION_BYTES 32u
struct sophia_wf_projection_presentation {
    uint64_t generation;
    uint64_t keyboard_output;
    uint16_t output_count;
    uint16_t binding_count;
    uint32_t instance_count;
    uint32_t region_count;
};
int sophia_wf_projection_presentation_decode(const void *, size_t, struct sophia_wf_projection_presentation *);
int sophia_wf_projection_presentation_encode(void *, size_t, const struct sophia_wf_projection_presentation *);
#define SOPHIA_WF_PROJECTION_PRESENTATION_OUTPUT_BYTES 40u
struct sophia_wf_projection_presentation_output {
    uint64_t output;
    uint64_t generation;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    uint16_t mode;
};
int sophia_wf_projection_presentation_output_decode(const void *, size_t, struct sophia_wf_projection_presentation_output *);
int sophia_wf_projection_presentation_output_encode(void *, size_t, const struct sophia_wf_projection_presentation_output *);
#define SOPHIA_WF_PROJECTION_SURFACE_INSTANCE_BYTES 80u
struct sophia_wf_projection_surface_instance {
    uint64_t id;
    uint64_t generation;
    uint64_t output;
    uint32_t source_index;
    uint32_t source_generation;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t clip_x;
    int32_t clip_y;
    int32_t clip_width;
    int32_t clip_height;
    uint16_t opacity_millis;
    uint16_t z_index;
    uint64_t action;
};
int sophia_wf_projection_surface_instance_decode(const void *, size_t, struct sophia_wf_projection_surface_instance *);
int sophia_wf_projection_surface_instance_encode(void *, size_t, const struct sophia_wf_projection_surface_instance *);
#define SOPHIA_WF_PROJECTION_PRESENTATION_REGION_BYTES 72u
struct sophia_wf_projection_presentation_region {
    uint64_t id;
    uint64_t generation;
    uint64_t output;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t clip_x;
    int32_t clip_y;
    int32_t clip_width;
    int32_t clip_height;
    uint16_t z_index;
    uint16_t role;
    uint64_t action;
};
int sophia_wf_projection_presentation_region_decode(const void *, size_t, struct sophia_wf_projection_presentation_region *);
int sophia_wf_projection_presentation_region_encode(void *, size_t, const struct sophia_wf_projection_presentation_region *);
#define SOPHIA_WF_PROJECTION_PRESENTATION_BINDING_BYTES 16u
struct sophia_wf_projection_presentation_binding {
    uint64_t action;
    uint32_t keycode;
    uint32_t modifiers;
};
int sophia_wf_projection_presentation_binding_decode(const void *, size_t, struct sophia_wf_projection_presentation_binding *);
int sophia_wf_projection_presentation_binding_encode(void *, size_t, const struct sophia_wf_projection_presentation_binding *);
#define SOPHIA_WF_CONFIGURATION_ACTION_LIFECYCLE_BYTES 16u
struct sophia_wf_configuration_action_lifecycle {
    uint64_t action;
    uint32_t held_ms;
};
int sophia_wf_configuration_action_lifecycle_decode(const void *, size_t, struct sophia_wf_configuration_action_lifecycle *);
int sophia_wf_configuration_action_lifecycle_encode(void *, size_t, const struct sophia_wf_configuration_action_lifecycle *);
#endif
